// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/dashboard/v1/dashboard.proto

package dashboardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NetworkInterfaceState indicates the connectivity state of a network entry.
type NetworkInterfaceState int32

const (
	NetworkInterfaceState_NETWORK_INTERFACE_STATE_UNSPECIFIED   NetworkInterfaceState = 0
	NetworkInterfaceState_NETWORK_INTERFACE_STATE_CONNECTED     NetworkInterfaceState = 1
	NetworkInterfaceState_NETWORK_INTERFACE_STATE_DISCONNECTED  NetworkInterfaceState = 2
	NetworkInterfaceState_NETWORK_INTERFACE_STATE_NOT_CONNECTED NetworkInterfaceState = 3
)

// Enum value maps for NetworkInterfaceState.
var (
	NetworkInterfaceState_name = map[int32]string{
		0: "NETWORK_INTERFACE_STATE_UNSPECIFIED",
		1: "NETWORK_INTERFACE_STATE_CONNECTED",
		2: "NETWORK_INTERFACE_STATE_DISCONNECTED",
		3: "NETWORK_INTERFACE_STATE_NOT_CONNECTED",
	}
	NetworkInterfaceState_value = map[string]int32{
		"NETWORK_INTERFACE_STATE_UNSPECIFIED":   0,
		"NETWORK_INTERFACE_STATE_CONNECTED":     1,
		"NETWORK_INTERFACE_STATE_DISCONNECTED":  2,
		"NETWORK_INTERFACE_STATE_NOT_CONNECTED": 3,
	}
)

func (x NetworkInterfaceState) Enum() *NetworkInterfaceState {
	p := new(NetworkInterfaceState)
	*p = x
	return p
}

func (x NetworkInterfaceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkInterfaceState) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_dashboard_v1_dashboard_proto_enumTypes[0].Descriptor()
}

func (NetworkInterfaceState) Type() protoreflect.EnumType {
	return &file_openmanet_dashboard_v1_dashboard_proto_enumTypes[0]
}

func (x NetworkInterfaceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkInterfaceState.Descriptor instead.
func (NetworkInterfaceState) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

// ServiceStatus indicates whether a monitored service is running or stopped.
type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED ServiceStatus = 0
	ServiceStatus_SERVICE_STATUS_RUNNING     ServiceStatus = 1
	ServiceStatus_SERVICE_STATUS_STOPPED     ServiceStatus = 2
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_RUNNING",
		2: "SERVICE_STATUS_STOPPED",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED": 0,
		"SERVICE_STATUS_RUNNING":     1,
		"SERVICE_STATUS_STOPPED":     2,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_dashboard_v1_dashboard_proto_enumTypes[1].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_openmanet_dashboard_v1_dashboard_proto_enumTypes[1]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

// QuickAction enumerates the actions a client may request.
type QuickAction int32

const (
	QuickAction_QUICK_ACTION_UNSPECIFIED        QuickAction = 0
	QuickAction_QUICK_ACTION_REBOOT_DEVICE      QuickAction = 1
	QuickAction_QUICK_ACTION_RESTART_NETWORK    QuickAction = 2
	QuickAction_QUICK_ACTION_RESTART_OPENMANETD QuickAction = 3
)

// Enum value maps for QuickAction.
var (
	QuickAction_name = map[int32]string{
		0: "QUICK_ACTION_UNSPECIFIED",
		1: "QUICK_ACTION_REBOOT_DEVICE",
		2: "QUICK_ACTION_RESTART_NETWORK",
		3: "QUICK_ACTION_RESTART_OPENMANETD",
	}
	QuickAction_value = map[string]int32{
		"QUICK_ACTION_UNSPECIFIED":        0,
		"QUICK_ACTION_REBOOT_DEVICE":      1,
		"QUICK_ACTION_RESTART_NETWORK":    2,
		"QUICK_ACTION_RESTART_OPENMANETD": 3,
	}
)

func (x QuickAction) Enum() *QuickAction {
	p := new(QuickAction)
	*p = x
	return p
}

func (x QuickAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuickAction) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_dashboard_v1_dashboard_proto_enumTypes[2].Descriptor()
}

func (QuickAction) Type() protoreflect.EnumType {
	return &file_openmanet_dashboard_v1_dashboard_proto_enumTypes[2]
}

func (x QuickAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuickAction.Descriptor instead.
func (QuickAction) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

// DeviceInfo describes the hardware and software identity of the device.
type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hostname of the device.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The hardware model name (e.g. "MorseMicro HaLowLink 2").
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// The firmware version string (e.g. "OpenWrt 23.05.3 / OpenMANET 1.7.0").
	Firmware string `protobuf:"bytes,3,opt,name=firmware,proto3" json:"firmware,omitempty"`
	// The Linux kernel version (e.g. "5.15.150").
	Kernel string `protobuf:"bytes,4,opt,name=kernel,proto3" json:"kernel,omitempty"`
	// The CPU architecture (e.g. "mipsel_24kc").
	Architecture  string `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *DeviceInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *DeviceInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

// SystemResources describes the current resource utilisation of the device.
type SystemResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time since last boot.
	Uptime *durationpb.Duration `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Current local wall-clock time on the device.
	LocalTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=local_time,json=localTime,proto3" json:"local_time,omitempty"`
	// Instantaneous CPU load expressed as a percentage (0–100).
	CpuLoadPercent float32 `protobuf:"fixed32,3,opt,name=cpu_load_percent,json=cpuLoadPercent,proto3" json:"cpu_load_percent,omitempty"`
	// Total physical memory in bytes.
	MemoryTotalBytes int64 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	// Currently used memory in bytes (total − available).
	MemoryUsedBytes int64 `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	// Total overlay filesystem capacity in bytes.
	OverlayTotalBytes int64 `protobuf:"varint,6,opt,name=overlay_total_bytes,json=overlayTotalBytes,proto3" json:"overlay_total_bytes,omitempty"`
	// Currently used overlay filesystem space in bytes.
	OverlayUsedBytes int64 `protobuf:"varint,7,opt,name=overlay_used_bytes,json=overlayUsedBytes,proto3" json:"overlay_used_bytes,omitempty"`
	// CPU temperature in degrees Celsius. Negative values mean the running
	// device does not expose a CPU thermal sensor.
	CpuTempCelsius float32 `protobuf:"fixed32,8,opt,name=cpu_temp_celsius,json=cpuTempCelsius,proto3" json:"cpu_temp_celsius,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemResources) Reset() {
	*x = SystemResources{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemResources) ProtoMessage() {}

func (x *SystemResources) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemResources.ProtoReflect.Descriptor instead.
func (*SystemResources) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *SystemResources) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *SystemResources) GetLocalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LocalTime
	}
	return nil
}

func (x *SystemResources) GetCpuLoadPercent() float32 {
	if x != nil {
		return x.CpuLoadPercent
	}
	return 0
}

func (x *SystemResources) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *SystemResources) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemResources) GetOverlayTotalBytes() int64 {
	if x != nil {
		return x.OverlayTotalBytes
	}
	return 0
}

func (x *SystemResources) GetOverlayUsedBytes() int64 {
	if x != nil {
		return x.OverlayUsedBytes
	}
	return 0
}

func (x *SystemResources) GetCpuTempCelsius() float32 {
	if x != nil {
		return x.CpuTempCelsius
	}
	return 0
}

// BatteryStatus reports the node's battery monitor, such as the INA219 on a
// UPS module, as exposed by the kernel hwmon subsystem.
type BatteryStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether a battery monitor was found. All other fields are zero when false.
	Present bool `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	// Battery (bus) voltage in volts.
	VoltageVolts float32 `protobuf:"fixed32,2,opt,name=voltage_volts,json=voltageVolts,proto3" json:"voltage_volts,omitempty"`
	// Current through the monitor's shunt in amps. The sign follows the
	// monitor's wiring, so it is not a reliable charge/discharge indicator.
	CurrentAmps float32 `protobuf:"fixed32,3,opt,name=current_amps,json=currentAmps,proto3" json:"current_amps,omitempty"`
	// Power in watts as reported by the monitor.
	PowerWatts float32 `protobuf:"fixed32,4,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	// Estimated state of charge (0–100) from the Li-ion voltage curve.
	// Negative when it cannot be estimated.
	ChargePercent float32 `protobuf:"fixed32,5,opt,name=charge_percent,json=chargePercent,proto3" json:"charge_percent,omitempty"`
	// Number of series Li-ion cells inferred from the voltage, used for the
	// charge estimate. Zero when unknown.
	CellCount     uint32 `protobuf:"varint,6,opt,name=cell_count,json=cellCount,proto3" json:"cell_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryStatus) Reset() {
	*x = BatteryStatus{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryStatus) ProtoMessage() {}

func (x *BatteryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryStatus.ProtoReflect.Descriptor instead.
func (*BatteryStatus) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *BatteryStatus) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *BatteryStatus) GetVoltageVolts() float32 {
	if x != nil {
		return x.VoltageVolts
	}
	return 0
}

func (x *BatteryStatus) GetCurrentAmps() float32 {
	if x != nil {
		return x.CurrentAmps
	}
	return 0
}

func (x *BatteryStatus) GetPowerWatts() float32 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *BatteryStatus) GetChargePercent() float32 {
	if x != nil {
		return x.ChargePercent
	}
	return 0
}

func (x *BatteryStatus) GetCellCount() uint32 {
	if x != nil {
		return x.CellCount
	}
	return 0
}

// NetworkSummaryEntry describes one line in the network summary panel.
type NetworkSummaryEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kernel interface name (e.g. "eth0", "br-ahwlan", "bat0").
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// A human-friendly label (e.g. "WAN (eth0)", "LAN (br-ahwlan)").
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Current connectivity state of this entry.
	State NetworkInterfaceState `protobuf:"varint,3,opt,name=state,proto3,enum=openmanet.dashboard.v1.NetworkInterfaceState" json:"state,omitempty"`
	// Free-form detail string shown next to the entry, such as an IP/CIDR,
	// "Connected — 3 neighbors", "4 originators", or "Not connected".
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// Cumulative received bytes counter from the kernel since interface
	// creation (netlink RX_BYTES). Zero when the interface does not exist
	// or carries no traffic.
	RxBytes uint64 `protobuf:"varint,5,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	// Cumulative transmitted bytes counter from the kernel since interface
	// creation (netlink TX_BYTES). Zero when the interface does not exist
	// or carries no traffic.
	TxBytes       uint64 `protobuf:"varint,6,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSummaryEntry) Reset() {
	*x = NetworkSummaryEntry{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSummaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSummaryEntry) ProtoMessage() {}

func (x *NetworkSummaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSummaryEntry.ProtoReflect.Descriptor instead.
func (*NetworkSummaryEntry) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkSummaryEntry) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkSummaryEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NetworkSummaryEntry) GetState() NetworkInterfaceState {
	if x != nil {
		return x.State
	}
	return NetworkInterfaceState_NETWORK_INTERFACE_STATE_UNSPECIFIED
}

func (x *NetworkSummaryEntry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *NetworkSummaryEntry) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkSummaryEntry) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

// NetworkSummary is the collection of network summary entries.
type NetworkSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per notable interface / subsystem.
	Entries       []*NetworkSummaryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSummary) Reset() {
	*x = NetworkSummary{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSummary) ProtoMessage() {}

func (x *NetworkSummary) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSummary.ProtoReflect.Descriptor instead.
func (*NetworkSummary) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkSummary) GetEntries() []*NetworkSummaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ServiceInfo describes the runtime state of a single system service.
type ServiceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service name (e.g. "openmanetd", "dnsmasq").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the service is currently running.
	Status ServiceStatus `protobuf:"varint,2,opt,name=status,proto3,enum=openmanet.dashboard.v1.ServiceStatus" json:"status,omitempty"`
	// The PID of the running process, or 0 if not running.
	Pid           int32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *ServiceInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// GetDashboardStatusResponse contains all data needed to render the dashboard.
type GetDashboardStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hardware and software identity.
	DeviceInfo *DeviceInfo `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	// Current resource utilisation.
	SystemResources *SystemResources `protobuf:"bytes,2,opt,name=system_resources,json=systemResources,proto3" json:"system_resources,omitempty"`
	// Network interface / subsystem summary.
	NetworkSummary *NetworkSummary `protobuf:"bytes,3,opt,name=network_summary,json=networkSummary,proto3" json:"network_summary,omitempty"`
	// Status of monitored system services.
	ActiveServices []*ServiceInfo `protobuf:"bytes,4,rep,name=active_services,json=activeServices,proto3" json:"active_services,omitempty"`
	// Battery monitor readings, when the device has one.
	Battery       *BatteryStatus `protobuf:"bytes,5,opt,name=battery,proto3" json:"battery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardStatusResponse) Reset() {
	*x = GetDashboardStatusResponse{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatusResponse) ProtoMessage() {}

func (x *GetDashboardStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardStatusResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *GetDashboardStatusResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *GetDashboardStatusResponse) GetSystemResources() *SystemResources {
	if x != nil {
		return x.SystemResources
	}
	return nil
}

func (x *GetDashboardStatusResponse) GetNetworkSummary() *NetworkSummary {
	if x != nil {
		return x.NetworkSummary
	}
	return nil
}

func (x *GetDashboardStatusResponse) GetActiveServices() []*ServiceInfo {
	if x != nil {
		return x.ActiveServices
	}
	return nil
}

func (x *GetDashboardStatusResponse) GetBattery() *BatteryStatus {
	if x != nil {
		return x.Battery
	}
	return nil
}

// ExecuteQuickActionRequest identifies the action to perform.
type ExecuteQuickActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action to execute.
	Action        QuickAction `protobuf:"varint,1,opt,name=action,proto3,enum=openmanet.dashboard.v1.QuickAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQuickActionRequest) Reset() {
	*x = ExecuteQuickActionRequest{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQuickActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQuickActionRequest) ProtoMessage() {}

func (x *ExecuteQuickActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQuickActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQuickActionRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteQuickActionRequest) GetAction() QuickAction {
	if x != nil {
		return x.Action
	}
	return QuickAction_QUICK_ACTION_UNSPECIFIED
}

// ExecuteQuickActionResponse reports the outcome of an action.
type ExecuteQuickActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the action was accepted and initiated.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Optional human-readable detail about the outcome.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQuickActionResponse) Reset() {
	*x = ExecuteQuickActionResponse{}
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQuickActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQuickActionResponse) ProtoMessage() {}

func (x *ExecuteQuickActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_dashboard_v1_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQuickActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQuickActionResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteQuickActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteQuickActionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_openmanet_dashboard_v1_dashboard_proto protoreflect.FileDescriptor

const file_openmanet_dashboard_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"&openmanet/dashboard/v1/dashboard.proto\x12\x16openmanet.dashboard.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1a\n" +
	"\bfirmware\x18\x03 \x01(\tR\bfirmware\x12\x16\n" +
	"\x06kernel\x18\x04 \x01(\tR\x06kernel\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\"\x8b\x03\n" +
	"\x0fSystemResources\x121\n" +
	"\x06uptime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x129\n" +
	"\n" +
	"local_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tlocalTime\x12(\n" +
	"\x10cpu_load_percent\x18\x03 \x01(\x02R\x0ecpuLoadPercent\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x03R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x03R\x0fmemoryUsedBytes\x12.\n" +
	"\x13overlay_total_bytes\x18\x06 \x01(\x03R\x11overlayTotalBytes\x12,\n" +
	"\x12overlay_used_bytes\x18\a \x01(\x03R\x10overlayUsedBytes\x12(\n" +
	"\x10cpu_temp_celsius\x18\b \x01(\x02R\x0ecpuTempCelsius\"\xd8\x01\n" +
	"\rBatteryStatus\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12#\n" +
	"\rvoltage_volts\x18\x02 \x01(\x02R\fvoltageVolts\x12!\n" +
	"\fcurrent_amps\x18\x03 \x01(\x02R\vcurrentAmps\x12\x1f\n" +
	"\vpower_watts\x18\x04 \x01(\x02R\n" +
	"powerWatts\x12%\n" +
	"\x0echarge_percent\x18\x05 \x01(\x02R\rchargePercent\x12\x1d\n" +
	"\n" +
	"cell_count\x18\x06 \x01(\rR\tcellCount\"\xf2\x01\n" +
	"\x13NetworkSummaryEntry\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12C\n" +
	"\x05state\x18\x03 \x01(\x0e2-.openmanet.dashboard.v1.NetworkInterfaceStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x19\n" +
	"\brx_bytes\x18\x05 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x06 \x01(\x04R\atxBytes\"W\n" +
	"\x0eNetworkSummary\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.openmanet.dashboard.v1.NetworkSummaryEntryR\aentries\"r\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.openmanet.dashboard.v1.ServiceStatusR\x06status\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"\x95\x03\n" +
	"\x1aGetDashboardStatusResponse\x12C\n" +
	"\vdevice_info\x18\x01 \x01(\v2\".openmanet.dashboard.v1.DeviceInfoR\n" +
	"deviceInfo\x12R\n" +
	"\x10system_resources\x18\x02 \x01(\v2'.openmanet.dashboard.v1.SystemResourcesR\x0fsystemResources\x12O\n" +
	"\x0fnetwork_summary\x18\x03 \x01(\v2&.openmanet.dashboard.v1.NetworkSummaryR\x0enetworkSummary\x12L\n" +
	"\x0factive_services\x18\x04 \x03(\v2#.openmanet.dashboard.v1.ServiceInfoR\x0eactiveServices\x12?\n" +
	"\abattery\x18\x05 \x01(\v2%.openmanet.dashboard.v1.BatteryStatusR\abattery\"X\n" +
	"\x19ExecuteQuickActionRequest\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.openmanet.dashboard.v1.QuickActionR\x06action\"a\n" +
	"\x1aExecuteQuickActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message*\xbc\x01\n" +
	"\x15NetworkInterfaceState\x12'\n" +
	"#NETWORK_INTERFACE_STATE_UNSPECIFIED\x10\x00\x12%\n" +
	"!NETWORK_INTERFACE_STATE_CONNECTED\x10\x01\x12(\n" +
	"$NETWORK_INTERFACE_STATE_DISCONNECTED\x10\x02\x12)\n" +
	"%NETWORK_INTERFACE_STATE_NOT_CONNECTED\x10\x03*g\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVICE_STATUS_RUNNING\x10\x01\x12\x1a\n" +
	"\x16SERVICE_STATUS_STOPPED\x10\x02*\x92\x01\n" +
	"\vQuickAction\x12\x1c\n" +
	"\x18QUICK_ACTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aQUICK_ACTION_REBOOT_DEVICE\x10\x01\x12 \n" +
	"\x1cQUICK_ACTION_RESTART_NETWORK\x10\x02\x12#\n" +
	"\x1fQUICK_ACTION_RESTART_OPENMANETD\x10\x03B\xf7\x01\n" +
	"\x1acom.openmanet.dashboard.v1B\x0eDashboardProtoP\x01ZOgithub.com/openmanet/openmanetd/internal/api/openmanet/dashboard/v1;dashboardv1\xa2\x02\x03ODX\xaa\x02\x16Openmanet.Dashboard.V1\xca\x02\x16Openmanet\\Dashboard\\V1\xe2\x02\"Openmanet\\Dashboard\\V1\\GPBMetadata\xea\x02\x18Openmanet::Dashboard::V1b\x06proto3"

var (
	file_openmanet_dashboard_v1_dashboard_proto_rawDescOnce sync.Once
	file_openmanet_dashboard_v1_dashboard_proto_rawDescData []byte
)

func file_openmanet_dashboard_v1_dashboard_proto_rawDescGZIP() []byte {
	file_openmanet_dashboard_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_openmanet_dashboard_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_dashboard_v1_dashboard_proto_rawDesc), len(file_openmanet_dashboard_v1_dashboard_proto_rawDesc)))
	})
	return file_openmanet_dashboard_v1_dashboard_proto_rawDescData
}

var file_openmanet_dashboard_v1_dashboard_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_openmanet_dashboard_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_openmanet_dashboard_v1_dashboard_proto_goTypes = []any{
	(NetworkInterfaceState)(0),         // 0: openmanet.dashboard.v1.NetworkInterfaceState
	(ServiceStatus)(0),                 // 1: openmanet.dashboard.v1.ServiceStatus
	(QuickAction)(0),                   // 2: openmanet.dashboard.v1.QuickAction
	(*DeviceInfo)(nil),                 // 3: openmanet.dashboard.v1.DeviceInfo
	(*SystemResources)(nil),            // 4: openmanet.dashboard.v1.SystemResources
	(*BatteryStatus)(nil),              // 5: openmanet.dashboard.v1.BatteryStatus
	(*NetworkSummaryEntry)(nil),        // 6: openmanet.dashboard.v1.NetworkSummaryEntry
	(*NetworkSummary)(nil),             // 7: openmanet.dashboard.v1.NetworkSummary
	(*ServiceInfo)(nil),                // 8: openmanet.dashboard.v1.ServiceInfo
	(*GetDashboardStatusResponse)(nil), // 9: openmanet.dashboard.v1.GetDashboardStatusResponse
	(*ExecuteQuickActionRequest)(nil),  // 10: openmanet.dashboard.v1.ExecuteQuickActionRequest
	(*ExecuteQuickActionResponse)(nil), // 11: openmanet.dashboard.v1.ExecuteQuickActionResponse
	(*durationpb.Duration)(nil),        // 12: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_openmanet_dashboard_v1_dashboard_proto_depIdxs = []int32{
	12, // 0: openmanet.dashboard.v1.SystemResources.uptime:type_name -> google.protobuf.Duration
	13, // 1: openmanet.dashboard.v1.SystemResources.local_time:type_name -> google.protobuf.Timestamp
	0,  // 2: openmanet.dashboard.v1.NetworkSummaryEntry.state:type_name -> openmanet.dashboard.v1.NetworkInterfaceState
	6,  // 3: openmanet.dashboard.v1.NetworkSummary.entries:type_name -> openmanet.dashboard.v1.NetworkSummaryEntry
	1,  // 4: openmanet.dashboard.v1.ServiceInfo.status:type_name -> openmanet.dashboard.v1.ServiceStatus
	3,  // 5: openmanet.dashboard.v1.GetDashboardStatusResponse.device_info:type_name -> openmanet.dashboard.v1.DeviceInfo
	4,  // 6: openmanet.dashboard.v1.GetDashboardStatusResponse.system_resources:type_name -> openmanet.dashboard.v1.SystemResources
	7,  // 7: openmanet.dashboard.v1.GetDashboardStatusResponse.network_summary:type_name -> openmanet.dashboard.v1.NetworkSummary
	8,  // 8: openmanet.dashboard.v1.GetDashboardStatusResponse.active_services:type_name -> openmanet.dashboard.v1.ServiceInfo
	5,  // 9: openmanet.dashboard.v1.GetDashboardStatusResponse.battery:type_name -> openmanet.dashboard.v1.BatteryStatus
	2,  // 10: openmanet.dashboard.v1.ExecuteQuickActionRequest.action:type_name -> openmanet.dashboard.v1.QuickAction
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_openmanet_dashboard_v1_dashboard_proto_init() }
func file_openmanet_dashboard_v1_dashboard_proto_init() {
	if File_openmanet_dashboard_v1_dashboard_proto != nil {
		return
	}
	file_openmanet_dashboard_v1_dashboard_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_dashboard_v1_dashboard_proto_rawDesc), len(file_openmanet_dashboard_v1_dashboard_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmanet_dashboard_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_openmanet_dashboard_v1_dashboard_proto_depIdxs,
		EnumInfos:         file_openmanet_dashboard_v1_dashboard_proto_enumTypes,
		MessageInfos:      file_openmanet_dashboard_v1_dashboard_proto_msgTypes,
	}.Build()
	File_openmanet_dashboard_v1_dashboard_proto = out.File
	file_openmanet_dashboard_v1_dashboard_proto_goTypes = nil
	file_openmanet_dashboard_v1_dashboard_proto_depIdxs = nil
}
