// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: openmanet/hardware/v1/hardware_service.proto

package hardwarev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openmanet/openmanetd/internal/api/openmanet/hardware/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HardwareServiceName is the fully-qualified name of the HardwareService service.
	HardwareServiceName = "openmanet.hardware.v1.HardwareService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HardwareServiceGetHardwareStatusProcedure is the fully-qualified name of the HardwareService's
	// GetHardwareStatus RPC.
	HardwareServiceGetHardwareStatusProcedure = "/openmanet.hardware.v1.HardwareService/GetHardwareStatus"
	// HardwareServiceStreamHardwareStatusProcedure is the fully-qualified name of the HardwareService's
	// StreamHardwareStatus RPC.
	HardwareServiceStreamHardwareStatusProcedure = "/openmanet.hardware.v1.HardwareService/StreamHardwareStatus"
	// HardwareServiceSetRadioPowerProcedure is the fully-qualified name of the HardwareService's
	// SetRadioPower RPC.
	HardwareServiceSetRadioPowerProcedure = "/openmanet.hardware.v1.HardwareService/SetRadioPower"
	// HardwareServiceSetRadioRfDisableProcedure is the fully-qualified name of the HardwareService's
	// SetRadioRfDisable RPC.
	HardwareServiceSetRadioRfDisableProcedure = "/openmanet.hardware.v1.HardwareService/SetRadioRfDisable"
	// HardwareServiceExecuteRadioRecoveryProcedure is the fully-qualified name of the HardwareService's
	// ExecuteRadioRecovery RPC.
	HardwareServiceExecuteRadioRecoveryProcedure = "/openmanet.hardware.v1.HardwareService/ExecuteRadioRecovery"
	// HardwareServiceListRecoveryEventsProcedure is the fully-qualified name of the HardwareService's
	// ListRecoveryEvents RPC.
	HardwareServiceListRecoveryEventsProcedure = "/openmanet.hardware.v1.HardwareService/ListRecoveryEvents"
	// HardwareServiceExecuteGnssResetProcedure is the fully-qualified name of the HardwareService's
	// ExecuteGnssReset RPC.
	HardwareServiceExecuteGnssResetProcedure = "/openmanet.hardware.v1.HardwareService/ExecuteGnssReset"
)

// HardwareServiceClient is a client for the openmanet.hardware.v1.HardwareService service.
type HardwareServiceClient interface {
	// GetHardwareStatus returns the current hardware manager view.
	GetHardwareStatus(context.Context, *emptypb.Empty) (*v1.GetHardwareStatusResponse, error)
	// StreamHardwareStatus sends the current status immediately, then again
	// whenever it changes, at most once per second.
	StreamHardwareStatus(context.Context, *v1.StreamHardwareStatusRequest) (*connect.ServerStreamForClient[v1.StreamHardwareStatusResponse], error)
	// SetRadioPower requests a radio rail on or off through its state machine.
	// A request to power on a RADIO_STATE_FAILED radio is refused; use
	// ExecuteRadioRecovery.
	SetRadioPower(context.Context, *v1.SetRadioPowerRequest) (*v1.SetRadioPowerResponse, error)
	// SetRadioRfDisable asserts or releases the hardware RF disable line.
	// Only Wi-Fi has one (WIFI_WDIS1_N, low = RF off).
	SetRadioRfDisable(context.Context, *v1.SetRadioRfDisableRequest) (*v1.SetRadioRfDisableResponse, error)
	// ExecuteRadioRecovery runs the recovery ladder from step 1 now, or clears
	// RADIO_STATE_FAILED and powers the radio on again.
	ExecuteRadioRecovery(context.Context, *v1.ExecuteRadioRecoveryRequest) (*v1.ExecuteRadioRecoveryResponse, error)
	// ListRecoveryEvents returns the newest entries of the bounded recovery
	// event ring, newest first.
	ListRecoveryEvents(context.Context, *v1.ListRecoveryEventsRequest) (*v1.ListRecoveryEventsResponse, error)
	// ExecuteGnssReset pulses GNSS_RESET_N low for 100 ms. The PPS line and
	// GNSS UART are never touched.
	ExecuteGnssReset(context.Context, *v1.ExecuteGnssResetRequest) (*v1.ExecuteGnssResetResponse, error)
}

// NewHardwareServiceClient constructs a client for the openmanet.hardware.v1.HardwareService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHardwareServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HardwareServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	hardwareServiceMethods := v1.File_openmanet_hardware_v1_hardware_service_proto.Services().ByName("HardwareService").Methods()
	return &hardwareServiceClient{
		getHardwareStatus: connect.NewClient[emptypb.Empty, v1.GetHardwareStatusResponse](
			httpClient,
			baseURL+HardwareServiceGetHardwareStatusProcedure,
			connect.WithSchema(hardwareServiceMethods.ByName("GetHardwareStatus")),
			connect.WithClientOptions(opts...),
		),
		streamHardwareStatus: connect.NewClient[v1.StreamHardwareStatusRequest, v1.StreamHardwareStatusResponse](
			httpClient,
			baseURL+HardwareServiceStreamHardwareStatusProcedure,
			connect.WithSchema(hardwareServiceMethods.ByName("StreamHardwareStatus")),
			connect.WithClientOptions(opts...),
		),
		setRadioPower: connect.NewClient[v1.SetRadioPowerRequest, v1.SetRadioPowerResponse](
			httpClient,
			baseURL+HardwareServiceSetRadioPowerProcedure,
			connect.WithSchema(hardwareServiceMethods.ByName("SetRadioPower")),
			connect.WithClientOptions(opts...),
		),
		setRadioRfDisable: connect.NewClient[v1.SetRadioRfDisableRequest, v1.SetRadioRfDisableResponse](
			httpClient,
			baseURL+HardwareServiceSetRadioRfDisableProcedure,
			connect.WithSchema(hardwareServiceMethods.ByName("SetRadioRfDisable")),
			connect.WithClientOptions(opts...),
		),
		executeRadioRecovery: connect.NewClient[v1.ExecuteRadioRecoveryRequest, v1.ExecuteRadioRecoveryResponse](
			httpClient,
			baseURL+HardwareServiceExecuteRadioRecoveryProcedure,
			connect.WithSchema(hardwareServiceMethods.ByName("ExecuteRadioRecovery")),
			connect.WithClientOptions(opts...),
		),
		listRecoveryEvents: connect.NewClient[v1.ListRecoveryEventsRequest, v1.ListRecoveryEventsResponse](
			httpClient,
			baseURL+HardwareServiceListRecoveryEventsProcedure,
			connect.WithSchema(hardwareServiceMethods.ByName("ListRecoveryEvents")),
			connect.WithClientOptions(opts...),
		),
		executeGnssReset: connect.NewClient[v1.ExecuteGnssResetRequest, v1.ExecuteGnssResetResponse](
			httpClient,
			baseURL+HardwareServiceExecuteGnssResetProcedure,
			connect.WithSchema(hardwareServiceMethods.ByName("ExecuteGnssReset")),
			connect.WithClientOptions(opts...),
		),
	}
}

// hardwareServiceClient implements HardwareServiceClient.
type hardwareServiceClient struct {
	getHardwareStatus    *connect.Client[emptypb.Empty, v1.GetHardwareStatusResponse]
	streamHardwareStatus *connect.Client[v1.StreamHardwareStatusRequest, v1.StreamHardwareStatusResponse]
	setRadioPower        *connect.Client[v1.SetRadioPowerRequest, v1.SetRadioPowerResponse]
	setRadioRfDisable    *connect.Client[v1.SetRadioRfDisableRequest, v1.SetRadioRfDisableResponse]
	executeRadioRecovery *connect.Client[v1.ExecuteRadioRecoveryRequest, v1.ExecuteRadioRecoveryResponse]
	listRecoveryEvents   *connect.Client[v1.ListRecoveryEventsRequest, v1.ListRecoveryEventsResponse]
	executeGnssReset     *connect.Client[v1.ExecuteGnssResetRequest, v1.ExecuteGnssResetResponse]
}

// GetHardwareStatus calls openmanet.hardware.v1.HardwareService.GetHardwareStatus.
func (c *hardwareServiceClient) GetHardwareStatus(ctx context.Context, req *emptypb.Empty) (*v1.GetHardwareStatusResponse, error) {
	response, err := c.getHardwareStatus.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// StreamHardwareStatus calls openmanet.hardware.v1.HardwareService.StreamHardwareStatus.
func (c *hardwareServiceClient) StreamHardwareStatus(ctx context.Context, req *v1.StreamHardwareStatusRequest) (*connect.ServerStreamForClient[v1.StreamHardwareStatusResponse], error) {
	return c.streamHardwareStatus.CallServerStream(ctx, connect.NewRequest(req))
}

// SetRadioPower calls openmanet.hardware.v1.HardwareService.SetRadioPower.
func (c *hardwareServiceClient) SetRadioPower(ctx context.Context, req *v1.SetRadioPowerRequest) (*v1.SetRadioPowerResponse, error) {
	response, err := c.setRadioPower.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetRadioRfDisable calls openmanet.hardware.v1.HardwareService.SetRadioRfDisable.
func (c *hardwareServiceClient) SetRadioRfDisable(ctx context.Context, req *v1.SetRadioRfDisableRequest) (*v1.SetRadioRfDisableResponse, error) {
	response, err := c.setRadioRfDisable.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ExecuteRadioRecovery calls openmanet.hardware.v1.HardwareService.ExecuteRadioRecovery.
func (c *hardwareServiceClient) ExecuteRadioRecovery(ctx context.Context, req *v1.ExecuteRadioRecoveryRequest) (*v1.ExecuteRadioRecoveryResponse, error) {
	response, err := c.executeRadioRecovery.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListRecoveryEvents calls openmanet.hardware.v1.HardwareService.ListRecoveryEvents.
func (c *hardwareServiceClient) ListRecoveryEvents(ctx context.Context, req *v1.ListRecoveryEventsRequest) (*v1.ListRecoveryEventsResponse, error) {
	response, err := c.listRecoveryEvents.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ExecuteGnssReset calls openmanet.hardware.v1.HardwareService.ExecuteGnssReset.
func (c *hardwareServiceClient) ExecuteGnssReset(ctx context.Context, req *v1.ExecuteGnssResetRequest) (*v1.ExecuteGnssResetResponse, error) {
	response, err := c.executeGnssReset.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// HardwareServiceHandler is an implementation of the openmanet.hardware.v1.HardwareService service.
type HardwareServiceHandler interface {
	// GetHardwareStatus returns the current hardware manager view.
	GetHardwareStatus(context.Context, *emptypb.Empty) (*v1.GetHardwareStatusResponse, error)
	// StreamHardwareStatus sends the current status immediately, then again
	// whenever it changes, at most once per second.
	StreamHardwareStatus(context.Context, *v1.StreamHardwareStatusRequest, *connect.ServerStream[v1.StreamHardwareStatusResponse]) error
	// SetRadioPower requests a radio rail on or off through its state machine.
	// A request to power on a RADIO_STATE_FAILED radio is refused; use
	// ExecuteRadioRecovery.
	SetRadioPower(context.Context, *v1.SetRadioPowerRequest) (*v1.SetRadioPowerResponse, error)
	// SetRadioRfDisable asserts or releases the hardware RF disable line.
	// Only Wi-Fi has one (WIFI_WDIS1_N, low = RF off).
	SetRadioRfDisable(context.Context, *v1.SetRadioRfDisableRequest) (*v1.SetRadioRfDisableResponse, error)
	// ExecuteRadioRecovery runs the recovery ladder from step 1 now, or clears
	// RADIO_STATE_FAILED and powers the radio on again.
	ExecuteRadioRecovery(context.Context, *v1.ExecuteRadioRecoveryRequest) (*v1.ExecuteRadioRecoveryResponse, error)
	// ListRecoveryEvents returns the newest entries of the bounded recovery
	// event ring, newest first.
	ListRecoveryEvents(context.Context, *v1.ListRecoveryEventsRequest) (*v1.ListRecoveryEventsResponse, error)
	// ExecuteGnssReset pulses GNSS_RESET_N low for 100 ms. The PPS line and
	// GNSS UART are never touched.
	ExecuteGnssReset(context.Context, *v1.ExecuteGnssResetRequest) (*v1.ExecuteGnssResetResponse, error)
}

// NewHardwareServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHardwareServiceHandler(svc HardwareServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	hardwareServiceMethods := v1.File_openmanet_hardware_v1_hardware_service_proto.Services().ByName("HardwareService").Methods()
	hardwareServiceGetHardwareStatusHandler := connect.NewUnaryHandlerSimple(
		HardwareServiceGetHardwareStatusProcedure,
		svc.GetHardwareStatus,
		connect.WithSchema(hardwareServiceMethods.ByName("GetHardwareStatus")),
		connect.WithHandlerOptions(opts...),
	)
	hardwareServiceStreamHardwareStatusHandler := connect.NewServerStreamHandlerSimple(
		HardwareServiceStreamHardwareStatusProcedure,
		svc.StreamHardwareStatus,
		connect.WithSchema(hardwareServiceMethods.ByName("StreamHardwareStatus")),
		connect.WithHandlerOptions(opts...),
	)
	hardwareServiceSetRadioPowerHandler := connect.NewUnaryHandlerSimple(
		HardwareServiceSetRadioPowerProcedure,
		svc.SetRadioPower,
		connect.WithSchema(hardwareServiceMethods.ByName("SetRadioPower")),
		connect.WithHandlerOptions(opts...),
	)
	hardwareServiceSetRadioRfDisableHandler := connect.NewUnaryHandlerSimple(
		HardwareServiceSetRadioRfDisableProcedure,
		svc.SetRadioRfDisable,
		connect.WithSchema(hardwareServiceMethods.ByName("SetRadioRfDisable")),
		connect.WithHandlerOptions(opts...),
	)
	hardwareServiceExecuteRadioRecoveryHandler := connect.NewUnaryHandlerSimple(
		HardwareServiceExecuteRadioRecoveryProcedure,
		svc.ExecuteRadioRecovery,
		connect.WithSchema(hardwareServiceMethods.ByName("ExecuteRadioRecovery")),
		connect.WithHandlerOptions(opts...),
	)
	hardwareServiceListRecoveryEventsHandler := connect.NewUnaryHandlerSimple(
		HardwareServiceListRecoveryEventsProcedure,
		svc.ListRecoveryEvents,
		connect.WithSchema(hardwareServiceMethods.ByName("ListRecoveryEvents")),
		connect.WithHandlerOptions(opts...),
	)
	hardwareServiceExecuteGnssResetHandler := connect.NewUnaryHandlerSimple(
		HardwareServiceExecuteGnssResetProcedure,
		svc.ExecuteGnssReset,
		connect.WithSchema(hardwareServiceMethods.ByName("ExecuteGnssReset")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openmanet.hardware.v1.HardwareService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HardwareServiceGetHardwareStatusProcedure:
			hardwareServiceGetHardwareStatusHandler.ServeHTTP(w, r)
		case HardwareServiceStreamHardwareStatusProcedure:
			hardwareServiceStreamHardwareStatusHandler.ServeHTTP(w, r)
		case HardwareServiceSetRadioPowerProcedure:
			hardwareServiceSetRadioPowerHandler.ServeHTTP(w, r)
		case HardwareServiceSetRadioRfDisableProcedure:
			hardwareServiceSetRadioRfDisableHandler.ServeHTTP(w, r)
		case HardwareServiceExecuteRadioRecoveryProcedure:
			hardwareServiceExecuteRadioRecoveryHandler.ServeHTTP(w, r)
		case HardwareServiceListRecoveryEventsProcedure:
			hardwareServiceListRecoveryEventsHandler.ServeHTTP(w, r)
		case HardwareServiceExecuteGnssResetProcedure:
			hardwareServiceExecuteGnssResetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHardwareServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHardwareServiceHandler struct{}

func (UnimplementedHardwareServiceHandler) GetHardwareStatus(context.Context, *emptypb.Empty) (*v1.GetHardwareStatusResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.hardware.v1.HardwareService.GetHardwareStatus is not implemented"))
}

func (UnimplementedHardwareServiceHandler) StreamHardwareStatus(context.Context, *v1.StreamHardwareStatusRequest, *connect.ServerStream[v1.StreamHardwareStatusResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.hardware.v1.HardwareService.StreamHardwareStatus is not implemented"))
}

func (UnimplementedHardwareServiceHandler) SetRadioPower(context.Context, *v1.SetRadioPowerRequest) (*v1.SetRadioPowerResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.hardware.v1.HardwareService.SetRadioPower is not implemented"))
}

func (UnimplementedHardwareServiceHandler) SetRadioRfDisable(context.Context, *v1.SetRadioRfDisableRequest) (*v1.SetRadioRfDisableResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.hardware.v1.HardwareService.SetRadioRfDisable is not implemented"))
}

func (UnimplementedHardwareServiceHandler) ExecuteRadioRecovery(context.Context, *v1.ExecuteRadioRecoveryRequest) (*v1.ExecuteRadioRecoveryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.hardware.v1.HardwareService.ExecuteRadioRecovery is not implemented"))
}

func (UnimplementedHardwareServiceHandler) ListRecoveryEvents(context.Context, *v1.ListRecoveryEventsRequest) (*v1.ListRecoveryEventsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.hardware.v1.HardwareService.ListRecoveryEvents is not implemented"))
}

func (UnimplementedHardwareServiceHandler) ExecuteGnssReset(context.Context, *v1.ExecuteGnssResetRequest) (*v1.ExecuteGnssResetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openmanet.hardware.v1.HardwareService.ExecuteGnssReset is not implemented"))
}
