// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/hardware/v1/hardware_service.proto

package hardwarev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetHardwareStatusResponse carries the hardware status.
type GetHardwareStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the current hardware manager view.
	Status        *HardwareStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHardwareStatusResponse) Reset() {
	*x = GetHardwareStatusResponse{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHardwareStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardwareStatusResponse) ProtoMessage() {}

func (x *GetHardwareStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardwareStatusResponse.ProtoReflect.Descriptor instead.
func (*GetHardwareStatusResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetHardwareStatusResponse) GetStatus() *HardwareStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// StreamHardwareStatusRequest is reserved for future stream options.
type StreamHardwareStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHardwareStatusRequest) Reset() {
	*x = StreamHardwareStatusRequest{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHardwareStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHardwareStatusRequest) ProtoMessage() {}

func (x *StreamHardwareStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHardwareStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamHardwareStatusRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{1}
}

// StreamHardwareStatusResponse carries one status update.
type StreamHardwareStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the hardware manager view at the time of the update.
	Status        *HardwareStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHardwareStatusResponse) Reset() {
	*x = StreamHardwareStatusResponse{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHardwareStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHardwareStatusResponse) ProtoMessage() {}

func (x *StreamHardwareStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHardwareStatusResponse.ProtoReflect.Descriptor instead.
func (*StreamHardwareStatusResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{2}
}

func (x *StreamHardwareStatusResponse) GetStatus() *HardwareStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// SetRadioPowerRequest selects a radio and its requested power.
type SetRadioPowerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// radio is the radio to switch.
	Radio Radio `protobuf:"varint,1,opt,name=radio,proto3,enum=openmanet.hardware.v1.Radio" json:"radio,omitempty"`
	// enabled requests the rail on (true) or off (false).
	Enabled       bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRadioPowerRequest) Reset() {
	*x = SetRadioPowerRequest{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRadioPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRadioPowerRequest) ProtoMessage() {}

func (x *SetRadioPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRadioPowerRequest.ProtoReflect.Descriptor instead.
func (*SetRadioPowerRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetRadioPowerRequest) GetRadio() Radio {
	if x != nil {
		return x.Radio
	}
	return Radio_RADIO_UNSPECIFIED
}

func (x *SetRadioPowerRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SetRadioPowerResponse returns the radio status after the request was
// recorded. The transition itself happens on the state machine's next step.
type SetRadioPowerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// radio is the radio's status.
	Radio         *RadioStatus `protobuf:"bytes,1,opt,name=radio,proto3" json:"radio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRadioPowerResponse) Reset() {
	*x = SetRadioPowerResponse{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRadioPowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRadioPowerResponse) ProtoMessage() {}

func (x *SetRadioPowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRadioPowerResponse.ProtoReflect.Descriptor instead.
func (*SetRadioPowerResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetRadioPowerResponse) GetRadio() *RadioStatus {
	if x != nil {
		return x.Radio
	}
	return nil
}

// SetRadioRfDisableRequest selects a radio and the RF disable state.
type SetRadioRfDisableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// radio must be RADIO_WIFI; HaLow has no RF disable line.
	Radio Radio `protobuf:"varint,1,opt,name=radio,proto3,enum=openmanet.hardware.v1.Radio" json:"radio,omitempty"`
	// disabled asserts the RF disable (true) or releases it (false).
	Disabled      bool `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRadioRfDisableRequest) Reset() {
	*x = SetRadioRfDisableRequest{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRadioRfDisableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRadioRfDisableRequest) ProtoMessage() {}

func (x *SetRadioRfDisableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRadioRfDisableRequest.ProtoReflect.Descriptor instead.
func (*SetRadioRfDisableRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{5}
}

func (x *SetRadioRfDisableRequest) GetRadio() Radio {
	if x != nil {
		return x.Radio
	}
	return Radio_RADIO_UNSPECIFIED
}

func (x *SetRadioRfDisableRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

// SetRadioRfDisableResponse returns the radio status after the request was
// recorded.
type SetRadioRfDisableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// radio is the radio's status.
	Radio         *RadioStatus `protobuf:"bytes,1,opt,name=radio,proto3" json:"radio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRadioRfDisableResponse) Reset() {
	*x = SetRadioRfDisableResponse{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRadioRfDisableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRadioRfDisableResponse) ProtoMessage() {}

func (x *SetRadioRfDisableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRadioRfDisableResponse.ProtoReflect.Descriptor instead.
func (*SetRadioRfDisableResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetRadioRfDisableResponse) GetRadio() *RadioStatus {
	if x != nil {
		return x.Radio
	}
	return nil
}

// ExecuteRadioRecoveryRequest selects the radio to recover.
type ExecuteRadioRecoveryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// radio is the radio to recover.
	Radio         Radio `protobuf:"varint,1,opt,name=radio,proto3,enum=openmanet.hardware.v1.Radio" json:"radio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRadioRecoveryRequest) Reset() {
	*x = ExecuteRadioRecoveryRequest{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRadioRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRadioRecoveryRequest) ProtoMessage() {}

func (x *ExecuteRadioRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRadioRecoveryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRadioRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteRadioRecoveryRequest) GetRadio() Radio {
	if x != nil {
		return x.Radio
	}
	return Radio_RADIO_UNSPECIFIED
}

// ExecuteRadioRecoveryResponse returns the radio status after the request
// was recorded.
type ExecuteRadioRecoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// radio is the radio's status.
	Radio         *RadioStatus `protobuf:"bytes,1,opt,name=radio,proto3" json:"radio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRadioRecoveryResponse) Reset() {
	*x = ExecuteRadioRecoveryResponse{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRadioRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRadioRecoveryResponse) ProtoMessage() {}

func (x *ExecuteRadioRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRadioRecoveryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteRadioRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteRadioRecoveryResponse) GetRadio() *RadioStatus {
	if x != nil {
		return x.Radio
	}
	return nil
}

// ListRecoveryEventsRequest filters the event ring.
type ListRecoveryEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// limit is the maximum number of events to return, 1 to 64. Zero returns
	// the whole ring.
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// radio keeps only events for this radio when set. Unspecified returns
	// every event, including node-level ones.
	Radio         Radio `protobuf:"varint,2,opt,name=radio,proto3,enum=openmanet.hardware.v1.Radio" json:"radio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecoveryEventsRequest) Reset() {
	*x = ListRecoveryEventsRequest{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecoveryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecoveryEventsRequest) ProtoMessage() {}

func (x *ListRecoveryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecoveryEventsRequest.ProtoReflect.Descriptor instead.
func (*ListRecoveryEventsRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListRecoveryEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRecoveryEventsRequest) GetRadio() Radio {
	if x != nil {
		return x.Radio
	}
	return Radio_RADIO_UNSPECIFIED
}

// ListRecoveryEventsResponse carries the selected events, newest first.
type ListRecoveryEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// events are the selected events, newest first.
	Events        []*RecoveryEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecoveryEventsResponse) Reset() {
	*x = ListRecoveryEventsResponse{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecoveryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecoveryEventsResponse) ProtoMessage() {}

func (x *ListRecoveryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecoveryEventsResponse.ProtoReflect.Descriptor instead.
func (*ListRecoveryEventsResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListRecoveryEventsResponse) GetEvents() []*RecoveryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// ExecuteGnssResetRequest is reserved for future reset options.
type ExecuteGnssResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteGnssResetRequest) Reset() {
	*x = ExecuteGnssResetRequest{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteGnssResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGnssResetRequest) ProtoMessage() {}

func (x *ExecuteGnssResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGnssResetRequest.ProtoReflect.Descriptor instead.
func (*ExecuteGnssResetRequest) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{11}
}

// ExecuteGnssResetResponse confirms the reset request.
type ExecuteGnssResetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requested_at is when the reset was queued; the pulse runs on the hardware
	// manager's next step and is recorded as a RECOVERY_STEP_GNSS_RESET event.
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteGnssResetResponse) Reset() {
	*x = ExecuteGnssResetResponse{}
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteGnssResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGnssResetResponse) ProtoMessage() {}

func (x *ExecuteGnssResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGnssResetResponse.ProtoReflect.Descriptor instead.
func (*ExecuteGnssResetResponse) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteGnssResetResponse) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

var File_openmanet_hardware_v1_hardware_service_proto protoreflect.FileDescriptor

const file_openmanet_hardware_v1_hardware_service_proto_rawDesc = "" +
	"\n" +
	",openmanet/hardware/v1/hardware_service.proto\x12\x15openmanet.hardware.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$openmanet/hardware/v1/hardware.proto\"Z\n" +
	"\x19GetHardwareStatusResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\v2%.openmanet.hardware.v1.HardwareStatusR\x06status\"\x1d\n" +
	"\x1bStreamHardwareStatusRequest\"]\n" +
	"\x1cStreamHardwareStatusResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\v2%.openmanet.hardware.v1.HardwareStatusR\x06status\"p\n" +
	"\x14SetRadioPowerRequest\x12>\n" +
	"\x05radio\x18\x01 \x01(\x0e2\x1c.openmanet.hardware.v1.RadioB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05radio\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"Q\n" +
	"\x15SetRadioPowerResponse\x128\n" +
	"\x05radio\x18\x01 \x01(\v2\".openmanet.hardware.v1.RadioStatusR\x05radio\"t\n" +
	"\x18SetRadioRfDisableRequest\x12<\n" +
	"\x05radio\x18\x01 \x01(\x0e2\x1c.openmanet.hardware.v1.RadioB\b\xbaH\x05\x82\x01\x02\x18\x02R\x05radio\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\"U\n" +
	"\x19SetRadioRfDisableResponse\x128\n" +
	"\x05radio\x18\x01 \x01(\v2\".openmanet.hardware.v1.RadioStatusR\x05radio\"]\n" +
	"\x1bExecuteRadioRecoveryRequest\x12>\n" +
	"\x05radio\x18\x01 \x01(\x0e2\x1c.openmanet.hardware.v1.RadioB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05radio\"X\n" +
	"\x1cExecuteRadioRecoveryResponse\x128\n" +
	"\x05radio\x18\x01 \x01(\v2\".openmanet.hardware.v1.RadioStatusR\x05radio\"x\n" +
	"\x19ListRecoveryEventsRequest\x12\x1d\n" +
	"\x05limit\x18\x01 \x01(\rB\a\xbaH\x04*\x02\x18@R\x05limit\x12<\n" +
	"\x05radio\x18\x02 \x01(\x0e2\x1c.openmanet.hardware.v1.RadioB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05radio\"Z\n" +
	"\x1aListRecoveryEventsResponse\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.openmanet.hardware.v1.RecoveryEventR\x06events\"\x19\n" +
	"\x17ExecuteGnssResetRequest\"Y\n" +
	"\x18ExecuteGnssResetResponse\x12=\n" +
	"\frequested_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt2\xc9\x06\n" +
	"\x0fHardwareService\x12]\n" +
	"\x11GetHardwareStatus\x12\x16.google.protobuf.Empty\x1a0.openmanet.hardware.v1.GetHardwareStatusResponse\x12\x81\x01\n" +
	"\x14StreamHardwareStatus\x122.openmanet.hardware.v1.StreamHardwareStatusRequest\x1a3.openmanet.hardware.v1.StreamHardwareStatusResponse0\x01\x12j\n" +
	"\rSetRadioPower\x12+.openmanet.hardware.v1.SetRadioPowerRequest\x1a,.openmanet.hardware.v1.SetRadioPowerResponse\x12v\n" +
	"\x11SetRadioRfDisable\x12/.openmanet.hardware.v1.SetRadioRfDisableRequest\x1a0.openmanet.hardware.v1.SetRadioRfDisableResponse\x12\x7f\n" +
	"\x14ExecuteRadioRecovery\x122.openmanet.hardware.v1.ExecuteRadioRecoveryRequest\x1a3.openmanet.hardware.v1.ExecuteRadioRecoveryResponse\x12y\n" +
	"\x12ListRecoveryEvents\x120.openmanet.hardware.v1.ListRecoveryEventsRequest\x1a1.openmanet.hardware.v1.ListRecoveryEventsResponse\x12s\n" +
	"\x10ExecuteGnssReset\x12..openmanet.hardware.v1.ExecuteGnssResetRequest\x1a/.openmanet.hardware.v1.ExecuteGnssResetResponseB\xf6\x01\n" +
	"\x19com.openmanet.hardware.v1B\x14HardwareServiceProtoP\x01ZMgithub.com/openmanet/openmanetd/internal/api/openmanet/hardware/v1;hardwarev1\xa2\x02\x03OHX\xaa\x02\x15Openmanet.Hardware.V1\xca\x02\x15Openmanet\\Hardware\\V1\xe2\x02!Openmanet\\Hardware\\V1\\GPBMetadata\xea\x02\x17Openmanet::Hardware::V1b\x06proto3"

var (
	file_openmanet_hardware_v1_hardware_service_proto_rawDescOnce sync.Once
	file_openmanet_hardware_v1_hardware_service_proto_rawDescData []byte
)

func file_openmanet_hardware_v1_hardware_service_proto_rawDescGZIP() []byte {
	file_openmanet_hardware_v1_hardware_service_proto_rawDescOnce.Do(func() {
		file_openmanet_hardware_v1_hardware_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_hardware_v1_hardware_service_proto_rawDesc), len(file_openmanet_hardware_v1_hardware_service_proto_rawDesc)))
	})
	return file_openmanet_hardware_v1_hardware_service_proto_rawDescData
}

var file_openmanet_hardware_v1_hardware_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_openmanet_hardware_v1_hardware_service_proto_goTypes = []any{
	(*GetHardwareStatusResponse)(nil),    // 0: openmanet.hardware.v1.GetHardwareStatusResponse
	(*StreamHardwareStatusRequest)(nil),  // 1: openmanet.hardware.v1.StreamHardwareStatusRequest
	(*StreamHardwareStatusResponse)(nil), // 2: openmanet.hardware.v1.StreamHardwareStatusResponse
	(*SetRadioPowerRequest)(nil),         // 3: openmanet.hardware.v1.SetRadioPowerRequest
	(*SetRadioPowerResponse)(nil),        // 4: openmanet.hardware.v1.SetRadioPowerResponse
	(*SetRadioRfDisableRequest)(nil),     // 5: openmanet.hardware.v1.SetRadioRfDisableRequest
	(*SetRadioRfDisableResponse)(nil),    // 6: openmanet.hardware.v1.SetRadioRfDisableResponse
	(*ExecuteRadioRecoveryRequest)(nil),  // 7: openmanet.hardware.v1.ExecuteRadioRecoveryRequest
	(*ExecuteRadioRecoveryResponse)(nil), // 8: openmanet.hardware.v1.ExecuteRadioRecoveryResponse
	(*ListRecoveryEventsRequest)(nil),    // 9: openmanet.hardware.v1.ListRecoveryEventsRequest
	(*ListRecoveryEventsResponse)(nil),   // 10: openmanet.hardware.v1.ListRecoveryEventsResponse
	(*ExecuteGnssResetRequest)(nil),      // 11: openmanet.hardware.v1.ExecuteGnssResetRequest
	(*ExecuteGnssResetResponse)(nil),     // 12: openmanet.hardware.v1.ExecuteGnssResetResponse
	(*HardwareStatus)(nil),               // 13: openmanet.hardware.v1.HardwareStatus
	(Radio)(0),                           // 14: openmanet.hardware.v1.Radio
	(*RadioStatus)(nil),                  // 15: openmanet.hardware.v1.RadioStatus
	(*RecoveryEvent)(nil),                // 16: openmanet.hardware.v1.RecoveryEvent
	(*timestamppb.Timestamp)(nil),        // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 18: google.protobuf.Empty
}
var file_openmanet_hardware_v1_hardware_service_proto_depIdxs = []int32{
	13, // 0: openmanet.hardware.v1.GetHardwareStatusResponse.status:type_name -> openmanet.hardware.v1.HardwareStatus
	13, // 1: openmanet.hardware.v1.StreamHardwareStatusResponse.status:type_name -> openmanet.hardware.v1.HardwareStatus
	14, // 2: openmanet.hardware.v1.SetRadioPowerRequest.radio:type_name -> openmanet.hardware.v1.Radio
	15, // 3: openmanet.hardware.v1.SetRadioPowerResponse.radio:type_name -> openmanet.hardware.v1.RadioStatus
	14, // 4: openmanet.hardware.v1.SetRadioRfDisableRequest.radio:type_name -> openmanet.hardware.v1.Radio
	15, // 5: openmanet.hardware.v1.SetRadioRfDisableResponse.radio:type_name -> openmanet.hardware.v1.RadioStatus
	14, // 6: openmanet.hardware.v1.ExecuteRadioRecoveryRequest.radio:type_name -> openmanet.hardware.v1.Radio
	15, // 7: openmanet.hardware.v1.ExecuteRadioRecoveryResponse.radio:type_name -> openmanet.hardware.v1.RadioStatus
	14, // 8: openmanet.hardware.v1.ListRecoveryEventsRequest.radio:type_name -> openmanet.hardware.v1.Radio
	16, // 9: openmanet.hardware.v1.ListRecoveryEventsResponse.events:type_name -> openmanet.hardware.v1.RecoveryEvent
	17, // 10: openmanet.hardware.v1.ExecuteGnssResetResponse.requested_at:type_name -> google.protobuf.Timestamp
	18, // 11: openmanet.hardware.v1.HardwareService.GetHardwareStatus:input_type -> google.protobuf.Empty
	1,  // 12: openmanet.hardware.v1.HardwareService.StreamHardwareStatus:input_type -> openmanet.hardware.v1.StreamHardwareStatusRequest
	3,  // 13: openmanet.hardware.v1.HardwareService.SetRadioPower:input_type -> openmanet.hardware.v1.SetRadioPowerRequest
	5,  // 14: openmanet.hardware.v1.HardwareService.SetRadioRfDisable:input_type -> openmanet.hardware.v1.SetRadioRfDisableRequest
	7,  // 15: openmanet.hardware.v1.HardwareService.ExecuteRadioRecovery:input_type -> openmanet.hardware.v1.ExecuteRadioRecoveryRequest
	9,  // 16: openmanet.hardware.v1.HardwareService.ListRecoveryEvents:input_type -> openmanet.hardware.v1.ListRecoveryEventsRequest
	11, // 17: openmanet.hardware.v1.HardwareService.ExecuteGnssReset:input_type -> openmanet.hardware.v1.ExecuteGnssResetRequest
	0,  // 18: openmanet.hardware.v1.HardwareService.GetHardwareStatus:output_type -> openmanet.hardware.v1.GetHardwareStatusResponse
	2,  // 19: openmanet.hardware.v1.HardwareService.StreamHardwareStatus:output_type -> openmanet.hardware.v1.StreamHardwareStatusResponse
	4,  // 20: openmanet.hardware.v1.HardwareService.SetRadioPower:output_type -> openmanet.hardware.v1.SetRadioPowerResponse
	6,  // 21: openmanet.hardware.v1.HardwareService.SetRadioRfDisable:output_type -> openmanet.hardware.v1.SetRadioRfDisableResponse
	8,  // 22: openmanet.hardware.v1.HardwareService.ExecuteRadioRecovery:output_type -> openmanet.hardware.v1.ExecuteRadioRecoveryResponse
	10, // 23: openmanet.hardware.v1.HardwareService.ListRecoveryEvents:output_type -> openmanet.hardware.v1.ListRecoveryEventsResponse
	12, // 24: openmanet.hardware.v1.HardwareService.ExecuteGnssReset:output_type -> openmanet.hardware.v1.ExecuteGnssResetResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_openmanet_hardware_v1_hardware_service_proto_init() }
func file_openmanet_hardware_v1_hardware_service_proto_init() {
	if File_openmanet_hardware_v1_hardware_service_proto != nil {
		return
	}
	file_openmanet_hardware_v1_hardware_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_hardware_v1_hardware_service_proto_rawDesc), len(file_openmanet_hardware_v1_hardware_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmanet_hardware_v1_hardware_service_proto_goTypes,
		DependencyIndexes: file_openmanet_hardware_v1_hardware_service_proto_depIdxs,
		MessageInfos:      file_openmanet_hardware_v1_hardware_service_proto_msgTypes,
	}.Build()
	File_openmanet_hardware_v1_hardware_service_proto = out.File
	file_openmanet_hardware_v1_hardware_service_proto_goTypes = nil
	file_openmanet_hardware_v1_hardware_service_proto_depIdxs = nil
}
