// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openmanet/hardware/v1/hardware.proto

package hardwarev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Radio identifies one switchable mesh radio on the V1 carrier. GNSS has no
// power switch on V1 and is controlled only through ExecuteGnssReset.
type Radio int32

const (
	// RADIO_UNSPECIFIED is the zero value. In a RecoveryEvent it marks a
	// node-level event (host reset request, GNSS reset) that has no radio.
	Radio_RADIO_UNSPECIFIED Radio = 0
	// RADIO_HALOW is the 802.11ah radio (Gateworks GW16170) on the USB hub.
	Radio_RADIO_HALOW Radio = 1
	// RADIO_WIFI is the 802.11ax radio (AsiaRF AW7916-AED) on PCIe.
	Radio_RADIO_WIFI Radio = 2
)

// Enum value maps for Radio.
var (
	Radio_name = map[int32]string{
		0: "RADIO_UNSPECIFIED",
		1: "RADIO_HALOW",
		2: "RADIO_WIFI",
	}
	Radio_value = map[string]int32{
		"RADIO_UNSPECIFIED": 0,
		"RADIO_HALOW":       1,
		"RADIO_WIFI":        2,
	}
)

func (x Radio) Enum() *Radio {
	p := new(Radio)
	*p = x
	return p
}

func (x Radio) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Radio) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[0].Descriptor()
}

func (Radio) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[0]
}

func (x Radio) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Radio.Descriptor instead.
func (Radio) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{0}
}

// RadioState is the per-radio power state machine state.
type RadioState int32

const (
	// RADIO_STATE_UNSPECIFIED is the zero value and is never reported.
	RadioState_RADIO_STATE_UNSPECIFIED RadioState = 0
	// RADIO_STATE_UNMANAGED means the daemon observes the radio but does not
	// control it: actuation is disabled, the board was not detected, the
	// boot-loop guard tripped, or the radio's bus identity is not configured.
	// device_present and netdev_present are still reported.
	RadioState_RADIO_STATE_UNMANAGED RadioState = 1
	// RADIO_STATE_OFF means the rail is off by request (user, low battery).
	RadioState_RADIO_STATE_OFF RadioState = 2
	// RADIO_STATE_POWERING means the enable is high and the rail is settling.
	RadioState_RADIO_STATE_POWERING RadioState = 3
	// RADIO_STATE_ENUMERATING means the daemon is waiting for the bus device
	// and its network interface to appear.
	RadioState_RADIO_STATE_ENUMERATING RadioState = 4
	// RADIO_STATE_UP means the interface is present and health checks pass.
	RadioState_RADIO_STATE_UP RadioState = 5
	// RADIO_STATE_FAULT means the recovery ladder is running.
	RadioState_RADIO_STATE_FAULT RadioState = 6
	// RADIO_STATE_COOLDOWN means the rail is off, waiting for the power-cycle
	// backoff before the next power-on.
	RadioState_RADIO_STATE_COOLDOWN RadioState = 7
	// RADIO_STATE_FAILED means the ladder is exhausted and the radio is left
	// off until ExecuteRadioRecovery or a reboot.
	RadioState_RADIO_STATE_FAILED RadioState = 8
)

// Enum value maps for RadioState.
var (
	RadioState_name = map[int32]string{
		0: "RADIO_STATE_UNSPECIFIED",
		1: "RADIO_STATE_UNMANAGED",
		2: "RADIO_STATE_OFF",
		3: "RADIO_STATE_POWERING",
		4: "RADIO_STATE_ENUMERATING",
		5: "RADIO_STATE_UP",
		6: "RADIO_STATE_FAULT",
		7: "RADIO_STATE_COOLDOWN",
		8: "RADIO_STATE_FAILED",
	}
	RadioState_value = map[string]int32{
		"RADIO_STATE_UNSPECIFIED": 0,
		"RADIO_STATE_UNMANAGED":   1,
		"RADIO_STATE_OFF":         2,
		"RADIO_STATE_POWERING":    3,
		"RADIO_STATE_ENUMERATING": 4,
		"RADIO_STATE_UP":          5,
		"RADIO_STATE_FAULT":       6,
		"RADIO_STATE_COOLDOWN":    7,
		"RADIO_STATE_FAILED":      8,
	}
)

func (x RadioState) Enum() *RadioState {
	p := new(RadioState)
	*p = x
	return p
}

func (x RadioState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RadioState) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[1].Descriptor()
}

func (RadioState) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[1]
}

func (x RadioState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RadioState.Descriptor instead.
func (RadioState) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{1}
}

// StateReason explains why a radio entered its current state, and is also
// the trigger recorded on a RecoveryEvent.
type StateReason int32

const (
	// STATE_REASON_UNSPECIFIED is the zero value.
	StateReason_STATE_REASON_UNSPECIFIED StateReason = 0
	// STATE_REASON_NONE means no particular cause (normal progress).
	StateReason_STATE_REASON_NONE StateReason = 1
	// STATE_REASON_USER means an operator request through SetRadioPower.
	StateReason_STATE_REASON_USER StateReason = 2
	// STATE_REASON_LOW_BATTERY means the battery policy turned the radio off.
	StateReason_STATE_REASON_LOW_BATTERY StateReason = 3
	// STATE_REASON_ENUMERATION_TIMEOUT means the bus device or netdev did not
	// appear within its timeout.
	StateReason_STATE_REASON_ENUMERATION_TIMEOUT StateReason = 4
	// STATE_REASON_HEALTH_CHECK means the device or netdev disappeared while
	// the rail was on for longer than the health grace period.
	StateReason_STATE_REASON_HEALTH_CHECK StateReason = 5
	// STATE_REASON_FAULT_LINE means a hardware fault input asserted.
	StateReason_STATE_REASON_FAULT_LINE StateReason = 6
	// STATE_REASON_POWER means EFUSE_FAULT asserted or POWER_GOOD dropped.
	// This is a node power fault, not a radio fault; no power-cycling
	// happens until POWER_GOOD has been back for 5 s.
	StateReason_STATE_REASON_POWER StateReason = 7
	// STATE_REASON_MANUAL_RECOVERY means an operator ran ExecuteRadioRecovery.
	StateReason_STATE_REASON_MANUAL_RECOVERY StateReason = 8
	// STATE_REASON_LADDER_EXHAUSTED means every recovery step was used up.
	StateReason_STATE_REASON_LADDER_EXHAUSTED StateReason = 9
	// STATE_REASON_STARTUP means the state was adopted from the hardware when
	// the daemon started.
	StateReason_STATE_REASON_STARTUP StateReason = 10
	// STATE_REASON_CONTROL_DISABLED accompanies RADIO_STATE_UNMANAGED.
	StateReason_STATE_REASON_CONTROL_DISABLED StateReason = 11
)

// Enum value maps for StateReason.
var (
	StateReason_name = map[int32]string{
		0:  "STATE_REASON_UNSPECIFIED",
		1:  "STATE_REASON_NONE",
		2:  "STATE_REASON_USER",
		3:  "STATE_REASON_LOW_BATTERY",
		4:  "STATE_REASON_ENUMERATION_TIMEOUT",
		5:  "STATE_REASON_HEALTH_CHECK",
		6:  "STATE_REASON_FAULT_LINE",
		7:  "STATE_REASON_POWER",
		8:  "STATE_REASON_MANUAL_RECOVERY",
		9:  "STATE_REASON_LADDER_EXHAUSTED",
		10: "STATE_REASON_STARTUP",
		11: "STATE_REASON_CONTROL_DISABLED",
	}
	StateReason_value = map[string]int32{
		"STATE_REASON_UNSPECIFIED":         0,
		"STATE_REASON_NONE":                1,
		"STATE_REASON_USER":                2,
		"STATE_REASON_LOW_BATTERY":         3,
		"STATE_REASON_ENUMERATION_TIMEOUT": 4,
		"STATE_REASON_HEALTH_CHECK":        5,
		"STATE_REASON_FAULT_LINE":          6,
		"STATE_REASON_POWER":               7,
		"STATE_REASON_MANUAL_RECOVERY":     8,
		"STATE_REASON_LADDER_EXHAUSTED":    9,
		"STATE_REASON_STARTUP":             10,
		"STATE_REASON_CONTROL_DISABLED":    11,
	}
)

func (x StateReason) Enum() *StateReason {
	p := new(StateReason)
	*p = x
	return p
}

func (x StateReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateReason) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[2].Descriptor()
}

func (StateReason) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[2]
}

func (x StateReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateReason.Descriptor instead.
func (StateReason) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{2}
}

// ControlMode says whether the daemon may drive any hardware line.
type ControlMode int32

const (
	// CONTROL_MODE_UNSPECIFIED is the zero value and is never reported.
	ControlMode_CONTROL_MODE_UNSPECIFIED ControlMode = 0
	// CONTROL_MODE_TELEMETRY_ONLY means the daemon reads telemetry and drives
	// nothing. Control RPCs fail with FAILED_PRECONDITION.
	ControlMode_CONTROL_MODE_TELEMETRY_ONLY ControlMode = 1
	// CONTROL_MODE_ACTIVE means the radio state machines and recovery ladder
	// are driving GPIO and bus controls.
	ControlMode_CONTROL_MODE_ACTIVE ControlMode = 2
)

// Enum value maps for ControlMode.
var (
	ControlMode_name = map[int32]string{
		0: "CONTROL_MODE_UNSPECIFIED",
		1: "CONTROL_MODE_TELEMETRY_ONLY",
		2: "CONTROL_MODE_ACTIVE",
	}
	ControlMode_value = map[string]int32{
		"CONTROL_MODE_UNSPECIFIED":    0,
		"CONTROL_MODE_TELEMETRY_ONLY": 1,
		"CONTROL_MODE_ACTIVE":         2,
	}
)

func (x ControlMode) Enum() *ControlMode {
	p := new(ControlMode)
	*p = x
	return p
}

func (x ControlMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMode) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[3].Descriptor()
}

func (ControlMode) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[3]
}

func (x ControlMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMode.Descriptor instead.
func (ControlMode) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{3}
}

// ControlModeReason explains the control mode.
type ControlModeReason int32

const (
	// CONTROL_MODE_REASON_UNSPECIFIED is the zero value.
	ControlModeReason_CONTROL_MODE_REASON_UNSPECIFIED ControlModeReason = 0
	// CONTROL_MODE_REASON_NONE accompanies CONTROL_MODE_ACTIVE.
	ControlModeReason_CONTROL_MODE_REASON_NONE ControlModeReason = 1
	// CONTROL_MODE_REASON_ACTUATION_DISABLED means hardware.actuationEnable is
	// false in the daemon config (the default until the V1 pin mapping is
	// verified on hardware).
	ControlModeReason_CONTROL_MODE_REASON_ACTUATION_DISABLED ControlModeReason = 2
	// CONTROL_MODE_REASON_BOARD_NOT_DETECTED means the board is not a V1
	// carrier (board.json model.id is not "ghostnet,v1").
	ControlModeReason_CONTROL_MODE_REASON_BOARD_NOT_DETECTED ControlModeReason = 3
	// CONTROL_MODE_REASON_LINES_UNRESOLVED means a required GPIO line name was
	// not found in the device tree, or a line request failed.
	ControlModeReason_CONTROL_MODE_REASON_LINES_UNRESOLVED ControlModeReason = 4
	// CONTROL_MODE_REASON_BOOT_LOOP_GUARD means three or more recovery-caused
	// resets happened within one hour, so this boot is telemetry-only.
	ControlModeReason_CONTROL_MODE_REASON_BOOT_LOOP_GUARD ControlModeReason = 5
)

// Enum value maps for ControlModeReason.
var (
	ControlModeReason_name = map[int32]string{
		0: "CONTROL_MODE_REASON_UNSPECIFIED",
		1: "CONTROL_MODE_REASON_NONE",
		2: "CONTROL_MODE_REASON_ACTUATION_DISABLED",
		3: "CONTROL_MODE_REASON_BOARD_NOT_DETECTED",
		4: "CONTROL_MODE_REASON_LINES_UNRESOLVED",
		5: "CONTROL_MODE_REASON_BOOT_LOOP_GUARD",
	}
	ControlModeReason_value = map[string]int32{
		"CONTROL_MODE_REASON_UNSPECIFIED":        0,
		"CONTROL_MODE_REASON_NONE":               1,
		"CONTROL_MODE_REASON_ACTUATION_DISABLED": 2,
		"CONTROL_MODE_REASON_BOARD_NOT_DETECTED": 3,
		"CONTROL_MODE_REASON_LINES_UNRESOLVED":   4,
		"CONTROL_MODE_REASON_BOOT_LOOP_GUARD":    5,
	}
)

func (x ControlModeReason) Enum() *ControlModeReason {
	p := new(ControlModeReason)
	*p = x
	return p
}

func (x ControlModeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlModeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[4].Descriptor()
}

func (ControlModeReason) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[4]
}

func (x ControlModeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlModeReason.Descriptor instead.
func (ControlModeReason) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{4}
}

// RecoveryStep is one rung of the fault-recovery ladder, or another audited
// hardware action.
type RecoveryStep int32

const (
	// RECOVERY_STEP_UNSPECIFIED is the zero value.
	RecoveryStep_RECOVERY_STEP_UNSPECIFIED RecoveryStep = 0
	// RECOVERY_STEP_RESET_USB_DEVICE is ladder step 1 for HaLow: USB device
	// reset, then driver unbind and bind.
	RecoveryStep_RECOVERY_STEP_RESET_USB_DEVICE RecoveryStep = 1
	// RECOVERY_STEP_RESET_PCIE_FUNCTION is ladder step 1 for Wi-Fi: PCI
	// function reset, then remove and rescan.
	RecoveryStep_RECOVERY_STEP_RESET_PCIE_FUNCTION RecoveryStep = 2
	// RECOVERY_STEP_RESET_HUB is ladder step 2 (HaLow only): pulse
	// USB_HUB_RESET_N. Also drops the OpenVLM audio device.
	RecoveryStep_RECOVERY_STEP_RESET_HUB RecoveryStep = 3
	// RECOVERY_STEP_POWER_CYCLE is ladder step 3: rail off, cooldown, power on.
	RecoveryStep_RECOVERY_STEP_POWER_CYCLE RecoveryStep = 4
	// RECOVERY_STEP_HOST_RESET is ladder step 4: the daemon stops petting the
	// supervisor watchdog so the node resets.
	RecoveryStep_RECOVERY_STEP_HOST_RESET RecoveryStep = 5
	// RECOVERY_STEP_GNSS_RESET records a manual GNSS_RESET_N pulse.
	RecoveryStep_RECOVERY_STEP_GNSS_RESET RecoveryStep = 6
	// RECOVERY_STEP_POWER_OFF records a radio rail switched off by request.
	RecoveryStep_RECOVERY_STEP_POWER_OFF RecoveryStep = 7
	// RECOVERY_STEP_SHUTDOWN records a low-battery graceful shutdown.
	RecoveryStep_RECOVERY_STEP_SHUTDOWN RecoveryStep = 8
)

// Enum value maps for RecoveryStep.
var (
	RecoveryStep_name = map[int32]string{
		0: "RECOVERY_STEP_UNSPECIFIED",
		1: "RECOVERY_STEP_RESET_USB_DEVICE",
		2: "RECOVERY_STEP_RESET_PCIE_FUNCTION",
		3: "RECOVERY_STEP_RESET_HUB",
		4: "RECOVERY_STEP_POWER_CYCLE",
		5: "RECOVERY_STEP_HOST_RESET",
		6: "RECOVERY_STEP_GNSS_RESET",
		7: "RECOVERY_STEP_POWER_OFF",
		8: "RECOVERY_STEP_SHUTDOWN",
	}
	RecoveryStep_value = map[string]int32{
		"RECOVERY_STEP_UNSPECIFIED":         0,
		"RECOVERY_STEP_RESET_USB_DEVICE":    1,
		"RECOVERY_STEP_RESET_PCIE_FUNCTION": 2,
		"RECOVERY_STEP_RESET_HUB":           3,
		"RECOVERY_STEP_POWER_CYCLE":         4,
		"RECOVERY_STEP_HOST_RESET":          5,
		"RECOVERY_STEP_GNSS_RESET":          6,
		"RECOVERY_STEP_POWER_OFF":           7,
		"RECOVERY_STEP_SHUTDOWN":            8,
	}
)

func (x RecoveryStep) Enum() *RecoveryStep {
	p := new(RecoveryStep)
	*p = x
	return p
}

func (x RecoveryStep) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoveryStep) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[5].Descriptor()
}

func (RecoveryStep) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[5]
}

func (x RecoveryStep) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoveryStep.Descriptor instead.
func (RecoveryStep) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{5}
}

// RecoveryResult is the outcome of one recorded action.
type RecoveryResult int32

const (
	// RECOVERY_RESULT_UNSPECIFIED is the zero value.
	RecoveryResult_RECOVERY_RESULT_UNSPECIFIED RecoveryResult = 0
	// RECOVERY_RESULT_SUCCEEDED means the action was carried out. Whether the
	// radio came back is visible in its state afterwards.
	RecoveryResult_RECOVERY_RESULT_SUCCEEDED RecoveryResult = 1
	// RECOVERY_RESULT_FAILED means the action returned an error (see detail).
	RecoveryResult_RECOVERY_RESULT_FAILED RecoveryResult = 2
	// RECOVERY_RESULT_SKIPPED means a precondition blocked the action (rate
	// limit, active PTT transmit, policy disabled); the ladder moved on.
	RecoveryResult_RECOVERY_RESULT_SKIPPED RecoveryResult = 3
	// RECOVERY_RESULT_EXHAUSTED means the ladder ran out and the radio is now
	// RADIO_STATE_FAILED.
	RecoveryResult_RECOVERY_RESULT_EXHAUSTED RecoveryResult = 4
)

// Enum value maps for RecoveryResult.
var (
	RecoveryResult_name = map[int32]string{
		0: "RECOVERY_RESULT_UNSPECIFIED",
		1: "RECOVERY_RESULT_SUCCEEDED",
		2: "RECOVERY_RESULT_FAILED",
		3: "RECOVERY_RESULT_SKIPPED",
		4: "RECOVERY_RESULT_EXHAUSTED",
	}
	RecoveryResult_value = map[string]int32{
		"RECOVERY_RESULT_UNSPECIFIED": 0,
		"RECOVERY_RESULT_SUCCEEDED":   1,
		"RECOVERY_RESULT_FAILED":      2,
		"RECOVERY_RESULT_SKIPPED":     3,
		"RECOVERY_RESULT_EXHAUSTED":   4,
	}
)

func (x RecoveryResult) Enum() *RecoveryResult {
	p := new(RecoveryResult)
	*p = x
	return p
}

func (x RecoveryResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecoveryResult) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[6].Descriptor()
}

func (RecoveryResult) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[6]
}

func (x RecoveryResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecoveryResult.Descriptor instead.
func (RecoveryResult) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{6}
}

// FaultLine names one hardware status input.
type FaultLine int32

const (
	// FAULT_LINE_UNSPECIFIED is the zero value.
	FaultLine_FAULT_LINE_UNSPECIFIED FaultLine = 0
	// FAULT_LINE_HALOW_FAULT is HALOW_FAULT_N (GPIO6). Source unselected on V1.
	FaultLine_FAULT_LINE_HALOW_FAULT FaultLine = 1
	// FAULT_LINE_WIFI_FAULT is WIFI_FAULT_N (GPIO7). Source unselected on V1.
	FaultLine_FAULT_LINE_WIFI_FAULT FaultLine = 2
	// FAULT_LINE_POWER_GOOD is POWER_GOOD (GPIO12). Asserted means the eFuse
	// reports power NOT good.
	FaultLine_FAULT_LINE_POWER_GOOD FaultLine = 3
	// FAULT_LINE_EFUSE_FAULT is EFUSE_FAULT (GPIO13), TPS26633 FLT, active low.
	FaultLine_FAULT_LINE_EFUSE_FAULT FaultLine = 4
	// FAULT_LINE_HALOW_USB_FAULT is HALOW_USB_FAULT_N (GPIO24), hub-port
	// overcurrent for the HaLow radio.
	FaultLine_FAULT_LINE_HALOW_USB_FAULT FaultLine = 5
	// FAULT_LINE_VLM_USB_FAULT is VLM_USB_FAULT_N (GPIO25), OpenVLM port
	// overcurrent.
	FaultLine_FAULT_LINE_VLM_USB_FAULT FaultLine = 6
	// FAULT_LINE_INA228_ALERT is INA228_ALERT_N (GPIO20), the battery monitor's
	// hardware alert.
	FaultLine_FAULT_LINE_INA228_ALERT FaultLine = 7
	// FAULT_LINE_SUPERVISOR_WDO is SUPERVISOR_WDO (GPIO11), the TPS386000
	// watchdog output. Logged only.
	FaultLine_FAULT_LINE_SUPERVISOR_WDO FaultLine = 8
)

// Enum value maps for FaultLine.
var (
	FaultLine_name = map[int32]string{
		0: "FAULT_LINE_UNSPECIFIED",
		1: "FAULT_LINE_HALOW_FAULT",
		2: "FAULT_LINE_WIFI_FAULT",
		3: "FAULT_LINE_POWER_GOOD",
		4: "FAULT_LINE_EFUSE_FAULT",
		5: "FAULT_LINE_HALOW_USB_FAULT",
		6: "FAULT_LINE_VLM_USB_FAULT",
		7: "FAULT_LINE_INA228_ALERT",
		8: "FAULT_LINE_SUPERVISOR_WDO",
	}
	FaultLine_value = map[string]int32{
		"FAULT_LINE_UNSPECIFIED":     0,
		"FAULT_LINE_HALOW_FAULT":     1,
		"FAULT_LINE_WIFI_FAULT":      2,
		"FAULT_LINE_POWER_GOOD":      3,
		"FAULT_LINE_EFUSE_FAULT":     4,
		"FAULT_LINE_HALOW_USB_FAULT": 5,
		"FAULT_LINE_VLM_USB_FAULT":   6,
		"FAULT_LINE_INA228_ALERT":    7,
		"FAULT_LINE_SUPERVISOR_WDO":  8,
	}
)

func (x FaultLine) Enum() *FaultLine {
	p := new(FaultLine)
	*p = x
	return p
}

func (x FaultLine) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FaultLine) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[7].Descriptor()
}

func (FaultLine) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[7]
}

func (x FaultLine) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FaultLine.Descriptor instead.
func (FaultLine) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{7}
}

// LineState is the observed state of a fault input.
type LineState int32

const (
	// LINE_STATE_UNSPECIFIED is the zero value.
	LineState_LINE_STATE_UNSPECIFIED LineState = 0
	// LINE_STATE_UNAVAILABLE means the input is not requested (source not
	// selected, not listed in hardware.faultInputs, or the board was not
	// detected). An unavailable line is neither healthy nor faulted.
	LineState_LINE_STATE_UNAVAILABLE LineState = 1
	// LINE_STATE_NORMAL means the input is read and reports no fault.
	LineState_LINE_STATE_NORMAL LineState = 2
	// LINE_STATE_ASSERTED means the input is read and reports a fault.
	LineState_LINE_STATE_ASSERTED LineState = 3
)

// Enum value maps for LineState.
var (
	LineState_name = map[int32]string{
		0: "LINE_STATE_UNSPECIFIED",
		1: "LINE_STATE_UNAVAILABLE",
		2: "LINE_STATE_NORMAL",
		3: "LINE_STATE_ASSERTED",
	}
	LineState_value = map[string]int32{
		"LINE_STATE_UNSPECIFIED": 0,
		"LINE_STATE_UNAVAILABLE": 1,
		"LINE_STATE_NORMAL":      2,
		"LINE_STATE_ASSERTED":    3,
	}
)

func (x LineState) Enum() *LineState {
	p := new(LineState)
	*p = x
	return p
}

func (x LineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LineState) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[8].Descriptor()
}

func (LineState) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[8]
}

func (x LineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LineState.Descriptor instead.
func (LineState) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{8}
}

// BatteryLevel is the low-battery policy level for the V1 3S pack.
type BatteryLevel int32

const (
	// BATTERY_LEVEL_UNSPECIFIED is the zero value.
	BatteryLevel_BATTERY_LEVEL_UNSPECIFIED BatteryLevel = 0
	// BATTERY_LEVEL_UNKNOWN means no fresh reading, or the board's pack is not
	// the documented V1 3S pack, so no thresholds apply.
	BatteryLevel_BATTERY_LEVEL_UNKNOWN BatteryLevel = 1
	// BATTERY_LEVEL_NORMAL means above the warning threshold.
	BatteryLevel_BATTERY_LEVEL_NORMAL BatteryLevel = 2
	// BATTERY_LEVEL_WARNING means compensated pack voltage below 10.5 V for
	// 30 s.
	BatteryLevel_BATTERY_LEVEL_WARNING BatteryLevel = 3
	// BATTERY_LEVEL_CRITICAL means below 9.9 V for 30 s; Wi-Fi is turned off.
	BatteryLevel_BATTERY_LEVEL_CRITICAL BatteryLevel = 4
	// BATTERY_LEVEL_SHUTDOWN means below 9.6 V for 30 s; a graceful shutdown
	// is pending (performed only when hardware.batteryShutdownEnable is true).
	BatteryLevel_BATTERY_LEVEL_SHUTDOWN BatteryLevel = 5
)

// Enum value maps for BatteryLevel.
var (
	BatteryLevel_name = map[int32]string{
		0: "BATTERY_LEVEL_UNSPECIFIED",
		1: "BATTERY_LEVEL_UNKNOWN",
		2: "BATTERY_LEVEL_NORMAL",
		3: "BATTERY_LEVEL_WARNING",
		4: "BATTERY_LEVEL_CRITICAL",
		5: "BATTERY_LEVEL_SHUTDOWN",
	}
	BatteryLevel_value = map[string]int32{
		"BATTERY_LEVEL_UNSPECIFIED": 0,
		"BATTERY_LEVEL_UNKNOWN":     1,
		"BATTERY_LEVEL_NORMAL":      2,
		"BATTERY_LEVEL_WARNING":     3,
		"BATTERY_LEVEL_CRITICAL":    4,
		"BATTERY_LEVEL_SHUTDOWN":    5,
	}
)

func (x BatteryLevel) Enum() *BatteryLevel {
	p := new(BatteryLevel)
	*p = x
	return p
}

func (x BatteryLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatteryLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[9].Descriptor()
}

func (BatteryLevel) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[9]
}

func (x BatteryLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatteryLevel.Descriptor instead.
func (BatteryLevel) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{9}
}

// BatteryAbsentReason explains why present is false.
type BatteryAbsentReason int32

const (
	// BATTERY_ABSENT_REASON_UNSPECIFIED is the zero value.
	BatteryAbsentReason_BATTERY_ABSENT_REASON_UNSPECIFIED BatteryAbsentReason = 0
	// BATTERY_ABSENT_REASON_NONE accompanies present = true.
	BatteryAbsentReason_BATTERY_ABSENT_REASON_NONE BatteryAbsentReason = 1
	// BATTERY_ABSENT_REASON_NO_MONITOR means no INA2xx hwmon device exists.
	BatteryAbsentReason_BATTERY_ABSENT_REASON_NO_MONITOR BatteryAbsentReason = 2
	// BATTERY_ABSENT_REASON_MONITOR_UNREACHABLE means the monitor exists but
	// no successful reading for more than 30 s (or never).
	BatteryAbsentReason_BATTERY_ABSENT_REASON_MONITOR_UNREACHABLE BatteryAbsentReason = 3
)

// Enum value maps for BatteryAbsentReason.
var (
	BatteryAbsentReason_name = map[int32]string{
		0: "BATTERY_ABSENT_REASON_UNSPECIFIED",
		1: "BATTERY_ABSENT_REASON_NONE",
		2: "BATTERY_ABSENT_REASON_NO_MONITOR",
		3: "BATTERY_ABSENT_REASON_MONITOR_UNREACHABLE",
	}
	BatteryAbsentReason_value = map[string]int32{
		"BATTERY_ABSENT_REASON_UNSPECIFIED":         0,
		"BATTERY_ABSENT_REASON_NONE":                1,
		"BATTERY_ABSENT_REASON_NO_MONITOR":          2,
		"BATTERY_ABSENT_REASON_MONITOR_UNREACHABLE": 3,
	}
)

func (x BatteryAbsentReason) Enum() *BatteryAbsentReason {
	p := new(BatteryAbsentReason)
	*p = x
	return p
}

func (x BatteryAbsentReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatteryAbsentReason) Descriptor() protoreflect.EnumDescriptor {
	return file_openmanet_hardware_v1_hardware_proto_enumTypes[10].Descriptor()
}

func (BatteryAbsentReason) Type() protoreflect.EnumType {
	return &file_openmanet_hardware_v1_hardware_proto_enumTypes[10]
}

func (x BatteryAbsentReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatteryAbsentReason.Descriptor instead.
func (BatteryAbsentReason) EnumDescriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{10}
}

// BatteryTelemetry is the INA228 battery-monitor block. The shunt sits after
// the eFuse and charger output, so these values measure system load, not
// battery current; while charging, current_ma is the node's draw.
type BatteryTelemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// present is true while a reading no older than 30 s exists.
	Present bool `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	// absent_reason explains present = false.
	AbsentReason BatteryAbsentReason `protobuf:"varint,2,opt,name=absent_reason,json=absentReason,proto3,enum=openmanet.hardware.v1.BatteryAbsentReason" json:"absent_reason,omitempty"`
	// stale is true when the newest reading is older than 5 s. Values are
	// kept (last good) while stale.
	Stale bool `protobuf:"varint,3,opt,name=stale,proto3" json:"stale,omitempty"`
	// sampled_at is when the values below were read. Unset when never read.
	SampledAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	// bus_voltage_mv is the bus voltage in millivolts (hwmon in1_input).
	BusVoltageMv int32 `protobuf:"varint,5,opt,name=bus_voltage_mv,json=busVoltageMv,proto3" json:"bus_voltage_mv,omitempty"`
	// current_ma is the system current in milliamps (hwmon curr1_input).
	// Positive is draw from the pack.
	CurrentMa int32 `protobuf:"varint,6,opt,name=current_ma,json=currentMa,proto3" json:"current_ma,omitempty"`
	// power_mw is the system power in milliwatts (hwmon power1_input / 1000).
	PowerMw int32 `protobuf:"varint,7,opt,name=power_mw,json=powerMw,proto3" json:"power_mw,omitempty"`
	// energy_mwh is the energy counted by the INA228 since its own power-up,
	// in milliwatt-hours (hwmon energy1_input). Unset when the driver lacks it.
	EnergyMwh *float64 `protobuf:"fixed64,8,opt,name=energy_mwh,json=energyMwh,proto3,oneof" json:"energy_mwh,omitempty"`
	// charge_mah is the charge drawn since the daemon started, in
	// milliamp-hours, integrated from current_ma. It is a coulomb count of
	// system draw, not battery state of charge, and is wrong while charging.
	ChargeMah float64 `protobuf:"fixed64,9,opt,name=charge_mah,json=chargeMah,proto3" json:"charge_mah,omitempty"`
	// monitor_temp_c is the INA228 die temperature in degrees Celsius (hwmon
	// temp1_input). Unset when the driver lacks it.
	MonitorTempC *float64 `protobuf:"fixed64,10,opt,name=monitor_temp_c,json=monitorTempC,proto3,oneof" json:"monitor_temp_c,omitempty"`
	// alarms is a bitmask of hwmon alarm flags: bit 0 in1_min_alarm (bus
	// undervoltage), bit 1 in0_max_alarm (shunt overvoltage), bit 2
	// power1_max_alarm, bit 3 temp1_max_alarm.
	Alarms uint32 `protobuf:"varint,11,opt,name=alarms,proto3" json:"alarms,omitempty"`
	// compensated_voltage_mv is V_bus + I x R_pack in millivolts, the value
	// compared with the low-battery thresholds.
	CompensatedVoltageMv int32 `protobuf:"varint,12,opt,name=compensated_voltage_mv,json=compensatedVoltageMv,proto3" json:"compensated_voltage_mv,omitempty"`
	// level is the low-battery policy level (with 30 s entry and 60 s / 0.2 V
	// hysteresis on exit).
	Level BatteryLevel `protobuf:"varint,13,opt,name=level,proto3,enum=openmanet.hardware.v1.BatteryLevel" json:"level,omitempty"`
	// series_cells is the pack's series cell count when known (3 on V1), else 0.
	SeriesCells   uint32 `protobuf:"varint,14,opt,name=series_cells,json=seriesCells,proto3" json:"series_cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryTelemetry) Reset() {
	*x = BatteryTelemetry{}
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryTelemetry) ProtoMessage() {}

func (x *BatteryTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryTelemetry.ProtoReflect.Descriptor instead.
func (*BatteryTelemetry) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{0}
}

func (x *BatteryTelemetry) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *BatteryTelemetry) GetAbsentReason() BatteryAbsentReason {
	if x != nil {
		return x.AbsentReason
	}
	return BatteryAbsentReason_BATTERY_ABSENT_REASON_UNSPECIFIED
}

func (x *BatteryTelemetry) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *BatteryTelemetry) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

func (x *BatteryTelemetry) GetBusVoltageMv() int32 {
	if x != nil {
		return x.BusVoltageMv
	}
	return 0
}

func (x *BatteryTelemetry) GetCurrentMa() int32 {
	if x != nil {
		return x.CurrentMa
	}
	return 0
}

func (x *BatteryTelemetry) GetPowerMw() int32 {
	if x != nil {
		return x.PowerMw
	}
	return 0
}

func (x *BatteryTelemetry) GetEnergyMwh() float64 {
	if x != nil && x.EnergyMwh != nil {
		return *x.EnergyMwh
	}
	return 0
}

func (x *BatteryTelemetry) GetChargeMah() float64 {
	if x != nil {
		return x.ChargeMah
	}
	return 0
}

func (x *BatteryTelemetry) GetMonitorTempC() float64 {
	if x != nil && x.MonitorTempC != nil {
		return *x.MonitorTempC
	}
	return 0
}

func (x *BatteryTelemetry) GetAlarms() uint32 {
	if x != nil {
		return x.Alarms
	}
	return 0
}

func (x *BatteryTelemetry) GetCompensatedVoltageMv() int32 {
	if x != nil {
		return x.CompensatedVoltageMv
	}
	return 0
}

func (x *BatteryTelemetry) GetLevel() BatteryLevel {
	if x != nil {
		return x.Level
	}
	return BatteryLevel_BATTERY_LEVEL_UNSPECIFIED
}

func (x *BatteryTelemetry) GetSeriesCells() uint32 {
	if x != nil {
		return x.SeriesCells
	}
	return 0
}

// FaultLineStatus reports one hardware status input.
type FaultLineStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// line identifies the input.
	Line FaultLine `protobuf:"varint,1,opt,name=line,proto3,enum=openmanet.hardware.v1.FaultLine" json:"line,omitempty"`
	// name is the device-tree GPIO line name, e.g. "POWER_GOOD".
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// state is the observed state.
	State LineState `protobuf:"varint,3,opt,name=state,proto3,enum=openmanet.hardware.v1.LineState" json:"state,omitempty"`
	// edges_total counts edges seen on this input since the daemon started.
	EdgesTotal uint64 `protobuf:"varint,4,opt,name=edges_total,json=edgesTotal,proto3" json:"edges_total,omitempty"`
	// last_change_at is when state last changed. Unset when it never changed.
	LastChangeAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_change_at,json=lastChangeAt,proto3" json:"last_change_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultLineStatus) Reset() {
	*x = FaultLineStatus{}
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultLineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultLineStatus) ProtoMessage() {}

func (x *FaultLineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultLineStatus.ProtoReflect.Descriptor instead.
func (*FaultLineStatus) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{1}
}

func (x *FaultLineStatus) GetLine() FaultLine {
	if x != nil {
		return x.Line
	}
	return FaultLine_FAULT_LINE_UNSPECIFIED
}

func (x *FaultLineStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FaultLineStatus) GetState() LineState {
	if x != nil {
		return x.State
	}
	return LineState_LINE_STATE_UNSPECIFIED
}

func (x *FaultLineStatus) GetEdgesTotal() uint64 {
	if x != nil {
		return x.EdgesTotal
	}
	return 0
}

func (x *FaultLineStatus) GetLastChangeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChangeAt
	}
	return nil
}

// RadioStatus reports one radio's state machine and recovery counters.
type RadioStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// radio identifies the radio.
	Radio Radio `protobuf:"varint,1,opt,name=radio,proto3,enum=openmanet.hardware.v1.Radio" json:"radio,omitempty"`
	// state is the current state machine state.
	State RadioState `protobuf:"varint,2,opt,name=state,proto3,enum=openmanet.hardware.v1.RadioState" json:"state,omitempty"`
	// reason explains why the radio entered state.
	Reason StateReason `protobuf:"varint,3,opt,name=reason,proto3,enum=openmanet.hardware.v1.StateReason" json:"reason,omitempty"`
	// state_since is when the radio entered state.
	StateSince *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=state_since,json=stateSince,proto3" json:"state_since,omitempty"`
	// power_requested is the operator's requested power (SetRadioPower). The
	// battery policy may still hold the radio off.
	PowerRequested bool `protobuf:"varint,5,opt,name=power_requested,json=powerRequested,proto3" json:"power_requested,omitempty"`
	// rf_disabled is true while the hardware RF disable is asserted (Wi-Fi
	// WIFI_WDIS1_N low). Always false for HaLow.
	RfDisabled bool `protobuf:"varint,6,opt,name=rf_disabled,json=rfDisabled,proto3" json:"rf_disabled,omitempty"`
	// device_present is true when the radio's bus device (USB or PCI) exists.
	DevicePresent bool `protobuf:"varint,7,opt,name=device_present,json=devicePresent,proto3" json:"device_present,omitempty"`
	// netdev_present is true when the radio's network interface exists.
	NetdevPresent bool `protobuf:"varint,8,opt,name=netdev_present,json=netdevPresent,proto3" json:"netdev_present,omitempty"`
	// netdev is the configured network interface name, empty when unset.
	Netdev string `protobuf:"bytes,9,opt,name=netdev,proto3" json:"netdev,omitempty"`
	// current_step is the next ladder step the radio will try while in
	// RADIO_STATE_FAULT, else unspecified.
	CurrentStep RecoveryStep `protobuf:"varint,10,opt,name=current_step,json=currentStep,proto3,enum=openmanet.hardware.v1.RecoveryStep" json:"current_step,omitempty"`
	// step_attempt is the number of attempts already made at current_step.
	StepAttempt uint32 `protobuf:"varint,11,opt,name=step_attempt,json=stepAttempt,proto3" json:"step_attempt,omitempty"`
	// next_action_at is when the state machine will next act on its own
	// (timer expiry). Unset when it is waiting on nothing.
	NextActionAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=next_action_at,json=nextActionAt,proto3" json:"next_action_at,omitempty"`
	// recoveries_total counts ladder steps run since the daemon started.
	RecoveriesTotal uint64 `protobuf:"varint,13,opt,name=recoveries_total,json=recoveriesTotal,proto3" json:"recoveries_total,omitempty"`
	// power_cycles_total counts ladder power cycles since the daemon started.
	PowerCyclesTotal uint64 `protobuf:"varint,14,opt,name=power_cycles_total,json=powerCyclesTotal,proto3" json:"power_cycles_total,omitempty"`
	// failed_total counts entries into RADIO_STATE_FAILED since the daemon
	// started.
	FailedTotal   uint64 `protobuf:"varint,15,opt,name=failed_total,json=failedTotal,proto3" json:"failed_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadioStatus) Reset() {
	*x = RadioStatus{}
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadioStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioStatus) ProtoMessage() {}

func (x *RadioStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioStatus.ProtoReflect.Descriptor instead.
func (*RadioStatus) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{2}
}

func (x *RadioStatus) GetRadio() Radio {
	if x != nil {
		return x.Radio
	}
	return Radio_RADIO_UNSPECIFIED
}

func (x *RadioStatus) GetState() RadioState {
	if x != nil {
		return x.State
	}
	return RadioState_RADIO_STATE_UNSPECIFIED
}

func (x *RadioStatus) GetReason() StateReason {
	if x != nil {
		return x.Reason
	}
	return StateReason_STATE_REASON_UNSPECIFIED
}

func (x *RadioStatus) GetStateSince() *timestamppb.Timestamp {
	if x != nil {
		return x.StateSince
	}
	return nil
}

func (x *RadioStatus) GetPowerRequested() bool {
	if x != nil {
		return x.PowerRequested
	}
	return false
}

func (x *RadioStatus) GetRfDisabled() bool {
	if x != nil {
		return x.RfDisabled
	}
	return false
}

func (x *RadioStatus) GetDevicePresent() bool {
	if x != nil {
		return x.DevicePresent
	}
	return false
}

func (x *RadioStatus) GetNetdevPresent() bool {
	if x != nil {
		return x.NetdevPresent
	}
	return false
}

func (x *RadioStatus) GetNetdev() string {
	if x != nil {
		return x.Netdev
	}
	return ""
}

func (x *RadioStatus) GetCurrentStep() RecoveryStep {
	if x != nil {
		return x.CurrentStep
	}
	return RecoveryStep_RECOVERY_STEP_UNSPECIFIED
}

func (x *RadioStatus) GetStepAttempt() uint32 {
	if x != nil {
		return x.StepAttempt
	}
	return 0
}

func (x *RadioStatus) GetNextActionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextActionAt
	}
	return nil
}

func (x *RadioStatus) GetRecoveriesTotal() uint64 {
	if x != nil {
		return x.RecoveriesTotal
	}
	return 0
}

func (x *RadioStatus) GetPowerCyclesTotal() uint64 {
	if x != nil {
		return x.PowerCyclesTotal
	}
	return 0
}

func (x *RadioStatus) GetFailedTotal() uint64 {
	if x != nil {
		return x.FailedTotal
	}
	return 0
}

// WatchdogStatus reports the supervisor watchdog service.
type WatchdogStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled is hardware.watchdogEnable from the daemon config.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// armed is true while the daemon holds the gpio-wdt device open and pets
	// it.
	Armed bool `protobuf:"varint,2,opt,name=armed,proto3" json:"armed,omitempty"`
	// device is the watchdog character device in use, e.g. "/dev/watchdog1".
	Device string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	// pets_total counts heartbeats written since the daemon started.
	PetsTotal uint64 `protobuf:"varint,4,opt,name=pets_total,json=petsTotal,proto3" json:"pets_total,omitempty"`
	// last_pet_at is when the last heartbeat was written.
	LastPetAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_pet_at,json=lastPetAt,proto3" json:"last_pet_at,omitempty"`
	// host_reset_requested is true once the daemon stopped petting to request
	// a host reset (ladder step 4).
	HostResetRequested bool `protobuf:"varint,6,opt,name=host_reset_requested,json=hostResetRequested,proto3" json:"host_reset_requested,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchdogStatus) Reset() {
	*x = WatchdogStatus{}
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchdogStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchdogStatus) ProtoMessage() {}

func (x *WatchdogStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchdogStatus.ProtoReflect.Descriptor instead.
func (*WatchdogStatus) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{3}
}

func (x *WatchdogStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WatchdogStatus) GetArmed() bool {
	if x != nil {
		return x.Armed
	}
	return false
}

func (x *WatchdogStatus) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *WatchdogStatus) GetPetsTotal() uint64 {
	if x != nil {
		return x.PetsTotal
	}
	return 0
}

func (x *WatchdogStatus) GetLastPetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPetAt
	}
	return nil
}

func (x *WatchdogStatus) GetHostResetRequested() bool {
	if x != nil {
		return x.HostResetRequested
	}
	return false
}

// HardwareStatus is the full hardware manager view.
type HardwareStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// generated_at is when this status was assembled.
	GeneratedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// board_detected is true when board.json identifies a V1 carrier.
	BoardDetected bool `protobuf:"varint,2,opt,name=board_detected,json=boardDetected,proto3" json:"board_detected,omitempty"`
	// control_mode says whether the daemon drives any hardware line.
	ControlMode ControlMode `protobuf:"varint,3,opt,name=control_mode,json=controlMode,proto3,enum=openmanet.hardware.v1.ControlMode" json:"control_mode,omitempty"`
	// control_mode_reason explains control_mode.
	ControlModeReason ControlModeReason `protobuf:"varint,4,opt,name=control_mode_reason,json=controlModeReason,proto3,enum=openmanet.hardware.v1.ControlModeReason" json:"control_mode_reason,omitempty"`
	// radios has one entry per switchable radio, HaLow first.
	Radios []*RadioStatus `protobuf:"bytes,5,rep,name=radios,proto3" json:"radios,omitempty"`
	// fault_lines has one entry per hardware status input, including
	// unavailable ones.
	FaultLines []*FaultLineStatus `protobuf:"bytes,6,rep,name=fault_lines,json=faultLines,proto3" json:"fault_lines,omitempty"`
	// power_fault is true while EFUSE_FAULT is asserted or POWER_GOOD is low,
	// or until POWER_GOOD has been back for 5 s.
	PowerFault bool `protobuf:"varint,7,opt,name=power_fault,json=powerFault,proto3" json:"power_fault,omitempty"`
	// battery is the battery-monitor block.
	Battery *BatteryTelemetry `protobuf:"bytes,8,opt,name=battery,proto3" json:"battery,omitempty"`
	// watchdog is the supervisor watchdog service.
	Watchdog *WatchdogStatus `protobuf:"bytes,9,opt,name=watchdog,proto3" json:"watchdog,omitempty"`
	// recovery_boots_last_hour counts recovery-caused resets recorded in the
	// last hour; three or more puts the boot in telemetry-only mode.
	RecoveryBootsLastHour uint32 `protobuf:"varint,10,opt,name=recovery_boots_last_hour,json=recoveryBootsLastHour,proto3" json:"recovery_boots_last_hour,omitempty"`
	// shutdown_pending is true once a low-battery graceful shutdown started.
	ShutdownPending bool `protobuf:"varint,11,opt,name=shutdown_pending,json=shutdownPending,proto3" json:"shutdown_pending,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HardwareStatus) Reset() {
	*x = HardwareStatus{}
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareStatus) ProtoMessage() {}

func (x *HardwareStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareStatus.ProtoReflect.Descriptor instead.
func (*HardwareStatus) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{4}
}

func (x *HardwareStatus) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *HardwareStatus) GetBoardDetected() bool {
	if x != nil {
		return x.BoardDetected
	}
	return false
}

func (x *HardwareStatus) GetControlMode() ControlMode {
	if x != nil {
		return x.ControlMode
	}
	return ControlMode_CONTROL_MODE_UNSPECIFIED
}

func (x *HardwareStatus) GetControlModeReason() ControlModeReason {
	if x != nil {
		return x.ControlModeReason
	}
	return ControlModeReason_CONTROL_MODE_REASON_UNSPECIFIED
}

func (x *HardwareStatus) GetRadios() []*RadioStatus {
	if x != nil {
		return x.Radios
	}
	return nil
}

func (x *HardwareStatus) GetFaultLines() []*FaultLineStatus {
	if x != nil {
		return x.FaultLines
	}
	return nil
}

func (x *HardwareStatus) GetPowerFault() bool {
	if x != nil {
		return x.PowerFault
	}
	return false
}

func (x *HardwareStatus) GetBattery() *BatteryTelemetry {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *HardwareStatus) GetWatchdog() *WatchdogStatus {
	if x != nil {
		return x.Watchdog
	}
	return nil
}

func (x *HardwareStatus) GetRecoveryBootsLastHour() uint32 {
	if x != nil {
		return x.RecoveryBootsLastHour
	}
	return 0
}

func (x *HardwareStatus) GetShutdownPending() bool {
	if x != nil {
		return x.ShutdownPending
	}
	return false
}

// RecoveryEvent is one entry of the bounded (64-entry) recovery event ring.
type RecoveryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// occurred_at is when the action started.
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// radio is the radio acted on; unspecified for node-level actions.
	Radio Radio `protobuf:"varint,2,opt,name=radio,proto3,enum=openmanet.hardware.v1.Radio" json:"radio,omitempty"`
	// step is the action taken.
	Step RecoveryStep `protobuf:"varint,3,opt,name=step,proto3,enum=openmanet.hardware.v1.RecoveryStep" json:"step,omitempty"`
	// attempt is the 1-based attempt number at this step for this incident.
	Attempt uint32 `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// trigger is why the action ran.
	Trigger StateReason `protobuf:"varint,5,opt,name=trigger,proto3,enum=openmanet.hardware.v1.StateReason" json:"trigger,omitempty"`
	// result is the outcome.
	Result RecoveryResult `protobuf:"varint,6,opt,name=result,proto3,enum=openmanet.hardware.v1.RecoveryResult" json:"result,omitempty"`
	// duration_ms is how long the action took, in milliseconds.
	DurationMs uint32 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// detail is a short human-readable note (error text or skip cause).
	Detail string `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`
	// caller is the authenticated user for operator-initiated actions, empty
	// for automatic ones.
	Caller        string `protobuf:"bytes,9,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryEvent) Reset() {
	*x = RecoveryEvent{}
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryEvent) ProtoMessage() {}

func (x *RecoveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openmanet_hardware_v1_hardware_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryEvent.ProtoReflect.Descriptor instead.
func (*RecoveryEvent) Descriptor() ([]byte, []int) {
	return file_openmanet_hardware_v1_hardware_proto_rawDescGZIP(), []int{5}
}

func (x *RecoveryEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *RecoveryEvent) GetRadio() Radio {
	if x != nil {
		return x.Radio
	}
	return Radio_RADIO_UNSPECIFIED
}

func (x *RecoveryEvent) GetStep() RecoveryStep {
	if x != nil {
		return x.Step
	}
	return RecoveryStep_RECOVERY_STEP_UNSPECIFIED
}

func (x *RecoveryEvent) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RecoveryEvent) GetTrigger() StateReason {
	if x != nil {
		return x.Trigger
	}
	return StateReason_STATE_REASON_UNSPECIFIED
}

func (x *RecoveryEvent) GetResult() RecoveryResult {
	if x != nil {
		return x.Result
	}
	return RecoveryResult_RECOVERY_RESULT_UNSPECIFIED
}

func (x *RecoveryEvent) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecoveryEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *RecoveryEvent) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

var File_openmanet_hardware_v1_hardware_proto protoreflect.FileDescriptor

const file_openmanet_hardware_v1_hardware_proto_rawDesc = "" +
	"\n" +
	"$openmanet/hardware/v1/hardware.proto\x12\x15openmanet.hardware.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x04\n" +
	"\x10BatteryTelemetry\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12O\n" +
	"\rabsent_reason\x18\x02 \x01(\x0e2*.openmanet.hardware.v1.BatteryAbsentReasonR\fabsentReason\x12\x14\n" +
	"\x05stale\x18\x03 \x01(\bR\x05stale\x129\n" +
	"\n" +
	"sampled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAt\x12$\n" +
	"\x0ebus_voltage_mv\x18\x05 \x01(\x05R\fbusVoltageMv\x12\x1d\n" +
	"\n" +
	"current_ma\x18\x06 \x01(\x05R\tcurrentMa\x12\x19\n" +
	"\bpower_mw\x18\a \x01(\x05R\apowerMw\x12\"\n" +
	"\n" +
	"energy_mwh\x18\b \x01(\x01H\x00R\tenergyMwh\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"charge_mah\x18\t \x01(\x01R\tchargeMah\x12)\n" +
	"\x0emonitor_temp_c\x18\n" +
	" \x01(\x01H\x01R\fmonitorTempC\x88\x01\x01\x12\x16\n" +
	"\x06alarms\x18\v \x01(\rR\x06alarms\x124\n" +
	"\x16compensated_voltage_mv\x18\f \x01(\x05R\x14compensatedVoltageMv\x129\n" +
	"\x05level\x18\r \x01(\x0e2#.openmanet.hardware.v1.BatteryLevelR\x05level\x12!\n" +
	"\fseries_cells\x18\x0e \x01(\rR\vseriesCellsB\r\n" +
	"\v_energy_mwhB\x11\n" +
	"\x0f_monitor_temp_c\"\xf6\x01\n" +
	"\x0fFaultLineStatus\x124\n" +
	"\x04line\x18\x01 \x01(\x0e2 .openmanet.hardware.v1.FaultLineR\x04line\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x05state\x18\x03 \x01(\x0e2 .openmanet.hardware.v1.LineStateR\x05state\x12\x1f\n" +
	"\vedges_total\x18\x04 \x01(\x04R\n" +
	"edgesTotal\x12@\n" +
	"\x0elast_change_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastChangeAt\"\xcc\x05\n" +
	"\vRadioStatus\x122\n" +
	"\x05radio\x18\x01 \x01(\x0e2\x1c.openmanet.hardware.v1.RadioR\x05radio\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.openmanet.hardware.v1.RadioStateR\x05state\x12:\n" +
	"\x06reason\x18\x03 \x01(\x0e2\".openmanet.hardware.v1.StateReasonR\x06reason\x12;\n" +
	"\vstate_since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"stateSince\x12'\n" +
	"\x0fpower_requested\x18\x05 \x01(\bR\x0epowerRequested\x12\x1f\n" +
	"\vrf_disabled\x18\x06 \x01(\bR\n" +
	"rfDisabled\x12%\n" +
	"\x0edevice_present\x18\a \x01(\bR\rdevicePresent\x12%\n" +
	"\x0enetdev_present\x18\b \x01(\bR\rnetdevPresent\x12\x16\n" +
	"\x06netdev\x18\t \x01(\tR\x06netdev\x12F\n" +
	"\fcurrent_step\x18\n" +
	" \x01(\x0e2#.openmanet.hardware.v1.RecoveryStepR\vcurrentStep\x12!\n" +
	"\fstep_attempt\x18\v \x01(\rR\vstepAttempt\x12@\n" +
	"\x0enext_action_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\fnextActionAt\x12)\n" +
	"\x10recoveries_total\x18\r \x01(\x04R\x0frecoveriesTotal\x12,\n" +
	"\x12power_cycles_total\x18\x0e \x01(\x04R\x10powerCyclesTotal\x12!\n" +
	"\ffailed_total\x18\x0f \x01(\x04R\vfailedTotal\"\xe5\x01\n" +
	"\x0eWatchdogStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05armed\x18\x02 \x01(\bR\x05armed\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"pets_total\x18\x04 \x01(\x04R\tpetsTotal\x12:\n" +
	"\vlast_pet_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastPetAt\x120\n" +
	"\x14host_reset_requested\x18\x06 \x01(\bR\x12hostResetRequested\"\xa7\x05\n" +
	"\x0eHardwareStatus\x12=\n" +
	"\fgenerated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12%\n" +
	"\x0eboard_detected\x18\x02 \x01(\bR\rboardDetected\x12E\n" +
	"\fcontrol_mode\x18\x03 \x01(\x0e2\".openmanet.hardware.v1.ControlModeR\vcontrolMode\x12X\n" +
	"\x13control_mode_reason\x18\x04 \x01(\x0e2(.openmanet.hardware.v1.ControlModeReasonR\x11controlModeReason\x12:\n" +
	"\x06radios\x18\x05 \x03(\v2\".openmanet.hardware.v1.RadioStatusR\x06radios\x12G\n" +
	"\vfault_lines\x18\x06 \x03(\v2&.openmanet.hardware.v1.FaultLineStatusR\n" +
	"faultLines\x12\x1f\n" +
	"\vpower_fault\x18\a \x01(\bR\n" +
	"powerFault\x12A\n" +
	"\abattery\x18\b \x01(\v2'.openmanet.hardware.v1.BatteryTelemetryR\abattery\x12A\n" +
	"\bwatchdog\x18\t \x01(\v2%.openmanet.hardware.v1.WatchdogStatusR\bwatchdog\x127\n" +
	"\x18recovery_boots_last_hour\x18\n" +
	" \x01(\rR\x15recoveryBootsLastHour\x12)\n" +
	"\x10shutdown_pending\x18\v \x01(\bR\x0fshutdownPending\"\xa1\x03\n" +
	"\rRecoveryEvent\x12;\n" +
	"\voccurred_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x122\n" +
	"\x05radio\x18\x02 \x01(\x0e2\x1c.openmanet.hardware.v1.RadioR\x05radio\x127\n" +
	"\x04step\x18\x03 \x01(\x0e2#.openmanet.hardware.v1.RecoveryStepR\x04step\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\rR\aattempt\x12<\n" +
	"\atrigger\x18\x05 \x01(\x0e2\".openmanet.hardware.v1.StateReasonR\atrigger\x12=\n" +
	"\x06result\x18\x06 \x01(\x0e2%.openmanet.hardware.v1.RecoveryResultR\x06result\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\rR\n" +
	"durationMs\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail\x12\x16\n" +
	"\x06caller\x18\t \x01(\tR\x06caller*?\n" +
	"\x05Radio\x12\x15\n" +
	"\x11RADIO_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vRADIO_HALOW\x10\x01\x12\x0e\n" +
	"\n" +
	"RADIO_WIFI\x10\x02*\xed\x01\n" +
	"\n" +
	"RadioState\x12\x1b\n" +
	"\x17RADIO_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RADIO_STATE_UNMANAGED\x10\x01\x12\x13\n" +
	"\x0fRADIO_STATE_OFF\x10\x02\x12\x18\n" +
	"\x14RADIO_STATE_POWERING\x10\x03\x12\x1b\n" +
	"\x17RADIO_STATE_ENUMERATING\x10\x04\x12\x12\n" +
	"\x0eRADIO_STATE_UP\x10\x05\x12\x15\n" +
	"\x11RADIO_STATE_FAULT\x10\x06\x12\x18\n" +
	"\x14RADIO_STATE_COOLDOWN\x10\a\x12\x16\n" +
	"\x12RADIO_STATE_FAILED\x10\b*\xf3\x02\n" +
	"\vStateReason\x12\x1c\n" +
	"\x18STATE_REASON_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STATE_REASON_NONE\x10\x01\x12\x15\n" +
	"\x11STATE_REASON_USER\x10\x02\x12\x1c\n" +
	"\x18STATE_REASON_LOW_BATTERY\x10\x03\x12$\n" +
	" STATE_REASON_ENUMERATION_TIMEOUT\x10\x04\x12\x1d\n" +
	"\x19STATE_REASON_HEALTH_CHECK\x10\x05\x12\x1b\n" +
	"\x17STATE_REASON_FAULT_LINE\x10\x06\x12\x16\n" +
	"\x12STATE_REASON_POWER\x10\a\x12 \n" +
	"\x1cSTATE_REASON_MANUAL_RECOVERY\x10\b\x12!\n" +
	"\x1dSTATE_REASON_LADDER_EXHAUSTED\x10\t\x12\x18\n" +
	"\x14STATE_REASON_STARTUP\x10\n" +
	"\x12!\n" +
	"\x1dSTATE_REASON_CONTROL_DISABLED\x10\v*e\n" +
	"\vControlMode\x12\x1c\n" +
	"\x18CONTROL_MODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCONTROL_MODE_TELEMETRY_ONLY\x10\x01\x12\x17\n" +
	"\x13CONTROL_MODE_ACTIVE\x10\x02*\x81\x02\n" +
	"\x11ControlModeReason\x12#\n" +
	"\x1fCONTROL_MODE_REASON_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONTROL_MODE_REASON_NONE\x10\x01\x12*\n" +
	"&CONTROL_MODE_REASON_ACTUATION_DISABLED\x10\x02\x12*\n" +
	"&CONTROL_MODE_REASON_BOARD_NOT_DETECTED\x10\x03\x12(\n" +
	"$CONTROL_MODE_REASON_LINES_UNRESOLVED\x10\x04\x12'\n" +
	"#CONTROL_MODE_REASON_BOOT_LOOP_GUARD\x10\x05*\xa9\x02\n" +
	"\fRecoveryStep\x12\x1d\n" +
	"\x19RECOVERY_STEP_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRECOVERY_STEP_RESET_USB_DEVICE\x10\x01\x12%\n" +
	"!RECOVERY_STEP_RESET_PCIE_FUNCTION\x10\x02\x12\x1b\n" +
	"\x17RECOVERY_STEP_RESET_HUB\x10\x03\x12\x1d\n" +
	"\x19RECOVERY_STEP_POWER_CYCLE\x10\x04\x12\x1c\n" +
	"\x18RECOVERY_STEP_HOST_RESET\x10\x05\x12\x1c\n" +
	"\x18RECOVERY_STEP_GNSS_RESET\x10\x06\x12\x1b\n" +
	"\x17RECOVERY_STEP_POWER_OFF\x10\a\x12\x1a\n" +
	"\x16RECOVERY_STEP_SHUTDOWN\x10\b*\xa8\x01\n" +
	"\x0eRecoveryResult\x12\x1f\n" +
	"\x1bRECOVERY_RESULT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RECOVERY_RESULT_SUCCEEDED\x10\x01\x12\x1a\n" +
	"\x16RECOVERY_RESULT_FAILED\x10\x02\x12\x1b\n" +
	"\x17RECOVERY_RESULT_SKIPPED\x10\x03\x12\x1d\n" +
	"\x19RECOVERY_RESULT_EXHAUSTED\x10\x04*\x8f\x02\n" +
	"\tFaultLine\x12\x1a\n" +
	"\x16FAULT_LINE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FAULT_LINE_HALOW_FAULT\x10\x01\x12\x19\n" +
	"\x15FAULT_LINE_WIFI_FAULT\x10\x02\x12\x19\n" +
	"\x15FAULT_LINE_POWER_GOOD\x10\x03\x12\x1a\n" +
	"\x16FAULT_LINE_EFUSE_FAULT\x10\x04\x12\x1e\n" +
	"\x1aFAULT_LINE_HALOW_USB_FAULT\x10\x05\x12\x1c\n" +
	"\x18FAULT_LINE_VLM_USB_FAULT\x10\x06\x12\x1b\n" +
	"\x17FAULT_LINE_INA228_ALERT\x10\a\x12\x1d\n" +
	"\x19FAULT_LINE_SUPERVISOR_WDO\x10\b*s\n" +
	"\tLineState\x12\x1a\n" +
	"\x16LINE_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LINE_STATE_UNAVAILABLE\x10\x01\x12\x15\n" +
	"\x11LINE_STATE_NORMAL\x10\x02\x12\x17\n" +
	"\x13LINE_STATE_ASSERTED\x10\x03*\xb5\x01\n" +
	"\fBatteryLevel\x12\x1d\n" +
	"\x19BATTERY_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BATTERY_LEVEL_UNKNOWN\x10\x01\x12\x18\n" +
	"\x14BATTERY_LEVEL_NORMAL\x10\x02\x12\x19\n" +
	"\x15BATTERY_LEVEL_WARNING\x10\x03\x12\x1a\n" +
	"\x16BATTERY_LEVEL_CRITICAL\x10\x04\x12\x1a\n" +
	"\x16BATTERY_LEVEL_SHUTDOWN\x10\x05*\xb1\x01\n" +
	"\x13BatteryAbsentReason\x12%\n" +
	"!BATTERY_ABSENT_REASON_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aBATTERY_ABSENT_REASON_NONE\x10\x01\x12$\n" +
	" BATTERY_ABSENT_REASON_NO_MONITOR\x10\x02\x12-\n" +
	")BATTERY_ABSENT_REASON_MONITOR_UNREACHABLE\x10\x03B\xef\x01\n" +
	"\x19com.openmanet.hardware.v1B\rHardwareProtoP\x01ZMgithub.com/openmanet/openmanetd/internal/api/openmanet/hardware/v1;hardwarev1\xa2\x02\x03OHX\xaa\x02\x15Openmanet.Hardware.V1\xca\x02\x15Openmanet\\Hardware\\V1\xe2\x02!Openmanet\\Hardware\\V1\\GPBMetadata\xea\x02\x17Openmanet::Hardware::V1b\x06proto3"

var (
	file_openmanet_hardware_v1_hardware_proto_rawDescOnce sync.Once
	file_openmanet_hardware_v1_hardware_proto_rawDescData []byte
)

func file_openmanet_hardware_v1_hardware_proto_rawDescGZIP() []byte {
	file_openmanet_hardware_v1_hardware_proto_rawDescOnce.Do(func() {
		file_openmanet_hardware_v1_hardware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmanet_hardware_v1_hardware_proto_rawDesc), len(file_openmanet_hardware_v1_hardware_proto_rawDesc)))
	})
	return file_openmanet_hardware_v1_hardware_proto_rawDescData
}

var file_openmanet_hardware_v1_hardware_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_openmanet_hardware_v1_hardware_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_openmanet_hardware_v1_hardware_proto_goTypes = []any{
	(Radio)(0),                    // 0: openmanet.hardware.v1.Radio
	(RadioState)(0),               // 1: openmanet.hardware.v1.RadioState
	(StateReason)(0),              // 2: openmanet.hardware.v1.StateReason
	(ControlMode)(0),              // 3: openmanet.hardware.v1.ControlMode
	(ControlModeReason)(0),        // 4: openmanet.hardware.v1.ControlModeReason
	(RecoveryStep)(0),             // 5: openmanet.hardware.v1.RecoveryStep
	(RecoveryResult)(0),           // 6: openmanet.hardware.v1.RecoveryResult
	(FaultLine)(0),                // 7: openmanet.hardware.v1.FaultLine
	(LineState)(0),                // 8: openmanet.hardware.v1.LineState
	(BatteryLevel)(0),             // 9: openmanet.hardware.v1.BatteryLevel
	(BatteryAbsentReason)(0),      // 10: openmanet.hardware.v1.BatteryAbsentReason
	(*BatteryTelemetry)(nil),      // 11: openmanet.hardware.v1.BatteryTelemetry
	(*FaultLineStatus)(nil),       // 12: openmanet.hardware.v1.FaultLineStatus
	(*RadioStatus)(nil),           // 13: openmanet.hardware.v1.RadioStatus
	(*WatchdogStatus)(nil),        // 14: openmanet.hardware.v1.WatchdogStatus
	(*HardwareStatus)(nil),        // 15: openmanet.hardware.v1.HardwareStatus
	(*RecoveryEvent)(nil),         // 16: openmanet.hardware.v1.RecoveryEvent
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_openmanet_hardware_v1_hardware_proto_depIdxs = []int32{
	10, // 0: openmanet.hardware.v1.BatteryTelemetry.absent_reason:type_name -> openmanet.hardware.v1.BatteryAbsentReason
	17, // 1: openmanet.hardware.v1.BatteryTelemetry.sampled_at:type_name -> google.protobuf.Timestamp
	9,  // 2: openmanet.hardware.v1.BatteryTelemetry.level:type_name -> openmanet.hardware.v1.BatteryLevel
	7,  // 3: openmanet.hardware.v1.FaultLineStatus.line:type_name -> openmanet.hardware.v1.FaultLine
	8,  // 4: openmanet.hardware.v1.FaultLineStatus.state:type_name -> openmanet.hardware.v1.LineState
	17, // 5: openmanet.hardware.v1.FaultLineStatus.last_change_at:type_name -> google.protobuf.Timestamp
	0,  // 6: openmanet.hardware.v1.RadioStatus.radio:type_name -> openmanet.hardware.v1.Radio
	1,  // 7: openmanet.hardware.v1.RadioStatus.state:type_name -> openmanet.hardware.v1.RadioState
	2,  // 8: openmanet.hardware.v1.RadioStatus.reason:type_name -> openmanet.hardware.v1.StateReason
	17, // 9: openmanet.hardware.v1.RadioStatus.state_since:type_name -> google.protobuf.Timestamp
	5,  // 10: openmanet.hardware.v1.RadioStatus.current_step:type_name -> openmanet.hardware.v1.RecoveryStep
	17, // 11: openmanet.hardware.v1.RadioStatus.next_action_at:type_name -> google.protobuf.Timestamp
	17, // 12: openmanet.hardware.v1.WatchdogStatus.last_pet_at:type_name -> google.protobuf.Timestamp
	17, // 13: openmanet.hardware.v1.HardwareStatus.generated_at:type_name -> google.protobuf.Timestamp
	3,  // 14: openmanet.hardware.v1.HardwareStatus.control_mode:type_name -> openmanet.hardware.v1.ControlMode
	4,  // 15: openmanet.hardware.v1.HardwareStatus.control_mode_reason:type_name -> openmanet.hardware.v1.ControlModeReason
	13, // 16: openmanet.hardware.v1.HardwareStatus.radios:type_name -> openmanet.hardware.v1.RadioStatus
	12, // 17: openmanet.hardware.v1.HardwareStatus.fault_lines:type_name -> openmanet.hardware.v1.FaultLineStatus
	11, // 18: openmanet.hardware.v1.HardwareStatus.battery:type_name -> openmanet.hardware.v1.BatteryTelemetry
	14, // 19: openmanet.hardware.v1.HardwareStatus.watchdog:type_name -> openmanet.hardware.v1.WatchdogStatus
	17, // 20: openmanet.hardware.v1.RecoveryEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0,  // 21: openmanet.hardware.v1.RecoveryEvent.radio:type_name -> openmanet.hardware.v1.Radio
	5,  // 22: openmanet.hardware.v1.RecoveryEvent.step:type_name -> openmanet.hardware.v1.RecoveryStep
	2,  // 23: openmanet.hardware.v1.RecoveryEvent.trigger:type_name -> openmanet.hardware.v1.StateReason
	6,  // 24: openmanet.hardware.v1.RecoveryEvent.result:type_name -> openmanet.hardware.v1.RecoveryResult
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_openmanet_hardware_v1_hardware_proto_init() }
func file_openmanet_hardware_v1_hardware_proto_init() {
	if File_openmanet_hardware_v1_hardware_proto != nil {
		return
	}
	file_openmanet_hardware_v1_hardware_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmanet_hardware_v1_hardware_proto_rawDesc), len(file_openmanet_hardware_v1_hardware_proto_rawDesc)),
			NumEnums:      11,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openmanet_hardware_v1_hardware_proto_goTypes,
		DependencyIndexes: file_openmanet_hardware_v1_hardware_proto_depIdxs,
		EnumInfos:         file_openmanet_hardware_v1_hardware_proto_enumTypes,
		MessageInfos:      file_openmanet_hardware_v1_hardware_proto_msgTypes,
	}.Build()
	File_openmanet_hardware_v1_hardware_proto = out.File
	file_openmanet_hardware_v1_hardware_proto_goTypes = nil
	file_openmanet_hardware_v1_hardware_proto_depIdxs = nil
}
